### ISSUE TITLE
Error in 0.92 [climate.smartir]: required key not provided @ data['controller_data']

### ISSUE THREAD

**Issue by remontti** [smartHomeHub/SmartIR#105]
**HA 0.92**
**SmartIR 1.4.1**

```
climate:
  - platform: smartir
    name: Climatizador
    device_code: 1360
    controller_send_service: 100.64.0.26
    temperature_sensor: sensor.suite_temperatura
    humidity_sensor: sensor.suite_umidade
```

_Error: Testing configuration at /config
Failed config
  climate.smartir: 
    - Invalid config for [climate.smartir]: required key not provided @ data['controller_data']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/climate.smartir/
    - platform: smartir
      controller_send_service: 100.64.0.26
      device_code: 1360
      humidity_sensor: sensor.suite_umidade
      name: Climatizador
      temperature_sensor: sensor.suite_temperatura
Successful config (partial)
  climate.smartir:_
