### ISSUE TITLE
self.async_update_ha_state(), without enabling force_update

### ISSUE THREAD

**Issue by Giga77** [smartHomeHub/SmartIR#1060]
**Home Assistant version**
core-2023.5.4

**SmartIR version**
1.17.6

**SmartIR configuration**

```yaml
climate:
  - platform: smartir
    name: Climatisation chambre 3
    unique_id: ac_ch3
    device_code: 1084
    controller_data: remote.remote_climatisation_chambre_3
    temperature_sensor: sensor.remote_climatisation_chambre_3_temperature
    humidity_sensor: sensor.remote_climatisation_chambre_3_humidity

```

**Describe the bug**

After updating HA to version 2023.5.4, there is a warning that appear in logs.

**Debug log**

```text

2023-06-08 09:54:15.212 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.climatisation_chambre_3 (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.

```
