### ISSUE TITLE
How to add more than one AC conditioner?

### ISSUE THREAD

**Issue by Cr4z33** [smartHomeHub/SmartIR#1067]
I tried figuring out setting up my three BroadLink that control my three air conditioners, but I keep seeing one AC entity only.

Here is how I am trying to integrate two of them (but only the first one can be seen):
```
climate:
  - platform: smartir
    name: Clima (Salone)
    unique_id: salone_ac
    device_code: 1880
    controller_data: remote.broadlink_rm_mini_3
  - platform: smartir
    name: Clima (Corridoio)
    unique_id: corridoio_ac
    device_code: 1880
    controller_data: remote.clima_corridoio_remote
```
