### ISSUE TITLE
HVAC: how to have a finer control than a whole degree?

### ISSUE THREAD

**Issue by unlucio** [smartHomeHub/SmartIR#1081]
**Home Assistant version**
2023.7.1

**SmartIR version**
1.17.7

**SmartIR configuration**

```yaml

smartir: 

climate:
  - platform: smartir
    name: Livingroom
    unique_id: livingroom
    device_code: 1101
    controller_data: remote.livingroom_ir_remote
    temperature_sensor: sensor.heater_temperature
  - platform: smartir
    name: Bedroom
    unique_id: bedroom
    device_code: 1101
    controller_data: remote.bedroom_ir_remote
    temperature_sensor: sensor.bedroom_temperature
    humidity_sensor: sensor.bedroom_humidity
  - platform: smartir
    name: Study
    unique_id: study
    device_code: 1101
    controller_data: remote.study_ir
    temperature_sensor: sensor.study_temperature

```

**Describe the bug**

Not exactly a bug but more of a refinement:
As per my configuration I'm using this set of commands: https://github.com/smartHomeHub/SmartIR/blob/master/codes/climate/1101.json
Unfortunately a whole degree granularity is not really cutting it: it's summer and 24ºC is too cold while 25ºC is yet not comfortable enough.
If I check on my original remotes they do allow for half a degree steps that are not encoded into the json file.
The climate control UI con HA allows for 0.1 steps but even setting, for instance, 24.5, doesn't seem to actually stop/star the AC at the right temperature

What would be the suggested way to achieve a comfortable temperature in my rooms?
