### ISSUE TITLE
power_sensor for FAN does not work

### ISSUE THREAD

**Issue by jokerigno** [smartHomeHub/SmartIR#1102]
**Home Assistant version**
Home Assistant 2023.7.3
**SmartIR version**
1.17.7
**SmartIR configuration**

```yaml

fan:
  - platform: smartir
    name: Ventilatore Cucina
    unique_id: kitchen_fan
    device_code: 9999
    controller_data: remote.rmini_cucina_remote
    power_sensor: binary_sensor.status_ventilatore

```

**Describe the bug**

Please notice that binary_sensor.status_ventilatore status is "on" when fan is on.

**Debug log**

Found in HA logs

```text

 Entity fan.ventilatore_cucina (<class 'custom_components.smartir.fan.SmartIRFan'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author. 

```

**Additional context**
