### ISSUE TITLE
Problem with oscilating loop & new codes for EGLO fans

### ISSUE THREAD

**Issue by dankarization** [smartHomeHub/SmartIR#1112]
**Home Assistant version**
2023.7.3
**SmartIR version**
1.17.7 (latest as of today)
**SmartIR configuration**

```yaml

smartir:
fan:
  #Вентилятор в гостиной
  - platform: smartir
    name: Вентилятор
    unique_id: lr_fan
    device_code: 1230
    controller_data: remote.broadlink_rm4_pro
  #Вентилятор в спальне
  - platform: smartir
    name: Вентилятор
    unique_id: br_fan
    device_code: 1231
    controller_data: remote.broadlink_rm4_pro

```

**Describe the bug**
I have 2 identical fans with different remotes and set of commands to control them individually. Both of them have 5 speeds and revert button (oscillate). When I just manually send commands, I can send oscillate only once, and then change speeds, turn them on/off and fan will stay.
It's enough to send oscillate command once, and it will be stored even after power outage.

If I turn on oscillate through fan entity created by SmartIR, every speed change will revert this fan, like I send oscillate command every time i change any setting on it

**Additional context**

Adding 2 files with codes for this model. People can relearn their fans to understand this codes instead of their own remote to save time reading these on their own.

[Архив.zip](https://github.com/smartHomeHub/SmartIR/files/12436924/default.zip)
