### ISSUE TITLE
self.async_update_ha_state()

### ISSUE THREAD

**Issue by kornelremete** [smartHomeHub/SmartIR#1117]
**Home Assistant version** 2023.8.4

**SmartIR version** 1.17.7

**SmartIR configuration**

```yaml

smartir:

climate:
  - platform: smartir
    name: Dining Room AC
    unique_id: dining_room_ac
    device_code: 1000
    controller_data: remote.broadlink_mini
    temperature_sensor: sensor.temperature_sensor_dining_room_temperature
    humidity_sensor: sensor.temperature_sensor_dining_room_humidity

```

**Describe the bug**

**Debug log**

```text

Add your logs here.

Entity climate.dining_room_ac (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.

**Additional context**

Add any other context about the problem here.

![2023-09-06_13h40_08](https://github.com/smartHomeHub/SmartIR/assets/64665925/c6bec3d8-eca0-45f9-b7e5-a0078230ada3)
