### ISSUE TITLE
Lost "source" attribute for media_player after turn off/on operation.

### ISSUE THREAD

**Issue by mrloggyst** [smartHomeHub/SmartIR#1122]
**Home Assistant version**: 2023.8.4

**SmartIR version**: 1.17.7

**SmartIR configuration**

```yaml
  - platform: smartir
    name: Living room Receiver
    unique_id: living_room_receiver
    device_code: 99998
    controller_data: remote.rm4c_pro_remote
    power_sensor: binary_sensor.av_receiver_power

```

**Describe the bug**
When media_player is turn on it is not restore state for "source" attribue. Attribute is absent.
After first change "source" is set to selected source value. But if again turn off/on then attribute "source" is lost.

**State when media_player is off:**

```yaml
source_list:
  - BD_DVD
  - VCR_DVR
  - CBL_SAT
  - GAME
  - AUX
  - TUNER
  - TV_CD
  - PORT
device_code: 99998
manufacturer: Onkyo
supported_models:
  - TX-SR578
supported_controller: Broadlink
commands_encoding: Base64
device_class: tv
friendly_name: Living room Receiver
supported_features: 3976
```
**State when media_player is on:**
```yaml
source_list:
  - BD_DVD
  - VCR_DVR
  - CBL_SAT
  - GAME
  - AUX
  - TUNER
  - TV_CD
  - PORT
device_code: 99998
manufacturer: Onkyo
supported_models:
  - TX-SR578
supported_controller: Broadlink
commands_encoding: Base64
device_class: tv
friendly_name: Living room Receiver
supported_features: 3976
media_content_type: channel
```
**State after change source when media_player is on:**
```yaml
source_list:
  - BD_DVD
  - VCR_DVR
  - CBL_SAT
  - GAME
  - AUX
  - TUNER
  - TV_CD
  - PORT
device_code: 99998
manufacturer: Onkyo
supported_models:
  - TX-SR578
supported_controller: Broadlink
commands_encoding: Base64
device_class: tv
friendly_name: Living room Receiver
supported_features: 3976
media_content_type: channel
source: PORT
```

**Additional context**

Trying to change to the same source value that will be before turn off and turn on, has no effect to attribute. Attribute not setting and not appear in the attribute list
