### ISSUE TITLE
Codes on Daikin 1101 JSON file (climate platform) learned with weekly option set to on

### ISSUE THREAD

**Issue by n0l1n3ry** [smartHomeHub/SmartIR#1184]
**Home Assistant version**  
2023.12.3

**SmartIR version**  
1.17.9

**SmartIR configuration**

```yaml
smartir:
  check_updates: false
climate:
  - platform: smartir
    name: AC Salon
    unique_id: livingroom_ac
    device_code: 1101
    controller_data: remote.rm_mini3_salon
    temperature_sensor: sensor.motion_sensor_air_temperature
    #humidity_sensor: sensor.humidity
    #power_sensor: binary_sensor.ac_power
```

**Describe the bug**

Not exactly a bug but the codes for 1101 (Daikin) seems to be learned with the **weekly** option (scheduler function) set to on.

When **weekly** is scheduled on an unit and a code is sent, the weekly option is also activated on the unit.

We can check it with the led on the unit panel which turns on when we send a code.

**Debug log**

N/A

**Additional context**

Tested on FTXS35G2V1B unit and Broadlink RM3 Mini with heat codes.  
The behavior is right if weekly option is not scheduled on the unit.
