### ISSUE TITLE
2x MSZ-GE25VAD2 - one of them works fine, the other will only turn off

### ISSUE THREAD

**Issue by nick-robinson-invenco** [smartHomeHub/SmartIR#1230]
Have two identical  MSZ-GE25VAD2 aircon units - one works fine, the other can only be turned off with SmartIr.  Same model remote as well.  Any ideas?

**Home Assistant version**
2024.3.3

**SmartIR version**
1.17.9

**SmartIR configuration**

```yaml

 - platform: smartir
    name: Master AC
    unique_id: master_ac
    device_code: 1135
    controller_data: remote.master_ir_blaster
#    temperature_sensor: sensor.temperature
#    humidity_sensor: sensor.humidity
#    power_sensor: binary_sensor.ac_power


  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac
    device_code: 1135
    controller_data: remote.bedroom_1ir_blaster
#    temperature_sensor: sensor.temperature
#    humidity_sensor: sensor.humidity
#    power_sensor: binary_sensor.ac_power


``` 
**Describe the bug**

Only Power off works  on one of these units - none of the other functions
