### ISSUE TITLE
.json file for Friedrich Remote Supports Models: AKB73756218, AKB73756215, AKB73756214, AKB73756213, CP05G10A, CP05G10B, CP12G10B, CP15G10A, CP15G30A, CP24G30B, EP08G11A, EP08G11B, EP12G33A, EP12G33B

### ISSUE THREAD

**Issue by Stromboli94** [smartHomeHub/SmartIR#1297]
[73756214.json](https://github.com/user-attachments/files/16445841/73756214.json)
Attached .json file works with Friedrich remote for models listed. [Amazon Listing](https://www.amazon.com/Replacement-Air-Conditioner-Remote-Control/dp/B072L26CZQ/ref=asc_df_B072L26CZQ/?gad_source=1&hvadid=692875362841&hvdev=c&hvdvcmdl&hvexpln=73&hvlocint&hvlocphy=9004447&hvnetw=g&hvocijid=2236554279940704615-B072L26CZQ-&hvpone&hvpos&hvptwo&hvqmt&hvrand=2236554279940704615&hvtargid=pla-2281435178058&linkCode=df0&mcid=b8e2eb0bcdc734e89d59e3a9dd3f7b77&psc=1&tag=hyprod-20)

Supported Models:
- AKB73756218
- AKB73756215
- AKB73756214
- AKB73756213
- CP05G10A
- CP05G10B
- CP12G10B
- CP15G10A
- CP15G30A
- CP24G30B
- EP08G11A
- EP08G11B
- EP12G33A
- EP12G33B

Temperature Range:
- Minimum temperature: 60
- Maximum temperature: 86

Operation modes:
- cool
- fan_only
- dry
- auto (this is the "money saver" mode, but needs to be a supported mode, so I named it 'auto')

Fan Modes:
- low
- medium
- high

Note: sending any of these codes will not turn on the air conditioner. They will only have an effect if the appliance is already turned on. 
To get around this, I created an ir switch from the broadlink integration to act as a virtual switch with a single on and off command. Put the following into ir_switches.yaml (and be sure the file is included in your configuration): 

```
switch:
  - platform: broadlink
    mac: MAC ADDRESS OF YOUR BROADLINK REMOTE (like aa:bb:cc:dd:ee:ff)
    switches:
      - name: AC Switch
        command_on: JgBAAF8AAT8QNA8SDxIQEg8zEBIREBIQEBEQMxAREBEQEhAzEDQREBIQDzQPEg8TDxIPNA8SEBIPEw8SDzQPEg8ADQU=
        command_off: JgBAAGAAAT8RMhIQDxIPEg81EBIPEhASDzMQMxASEBIPEg8SEBIQERAREBIQERASDxIQMxAREDMQEg8SEBIQMw8ADQU=
```
Add a climate device (from smart ir integration) as follows: 
```
climate:
  - platform: smartir
    name: My AC
    unique_id: my_ac
    device_code: 73756214
    controller_data: remote.my_universal_remote
    power_sensor: switch.ac_switch (this was created above)
```
Finally, create an automation to look for changes on the climate device which will turn on the appliance and set the states according to the information on the climate card: 
```
alias: AC Set State
description: Set state of ac when turned on
trigger:
  - platform: state
    entity_id:
      - climate.my_ac
    to: null
condition:
  - condition: template
    value_template: "{{ not (states('climate.my_ac') in ['unavailable','unknown']) }}"
action:
  - if:
      - condition: not
        conditions:
          - condition: state
            entity_id: climate.my_ac
            state: "off"
    then:
      - service: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.ac_switch
      - service: climate.set_fan_mode
        metadata: {}
        data:
          fan_mode: "{{ states.climate.my_ac.attributes.fan_mode }}"
        target:
          entity_id: climate.my_ac
      - if:
          - condition: not
            conditions:
              - condition: state
                entity_id: climate.my_ac
                state: "on"
        then:
          - service: climate.set_temperature
            metadata: {}
            data:
              hvac_mode: "{{ states('climate.my_ac') }}"
              temperature: "{{ states.climate.my_ac.attributes.temperature }}"
            target:
              entity_id: climate.my_ac
        else:
          - service: climate.set_temperature
            metadata: {}
            data:
              hvac_mode: auto
              temperature: "{{ states.climate.my_ac.attributes.temperature }}"
            target:
              entity_id: climate.my_ac
    else:
      - service: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: switch.ac_switch
mode: single

```

I used [broadlink-listener](https://github.com/gpongelli/broadlink-listener) to read the codes from my Broadlink RM Mini 3.
