### ISSUE TITLE
Device 2720 not working and lacking support for swing states

### ISSUE THREAD

**Issue by N0m4n904** [smartHomeHub/SmartIR#1310]
**Home Assistant version**
2024.8.3

**SmartIR version**
1.17.9

**SmartIR configuration**

```yaml

esphome:
  name: climate
  platform: ESP8266
  board: esp01_1m

api:
  encryption:
    key: XXXXXXX
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'

ota:
  platform: esphome
  password: XXXXXX

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Klimaanlage Fallback Hotspot"
    password: XXXXXXX

---------------HA---------------------

smartir:

climate:
  - platform: smartir
    name: "Noah Klimaanlage"
    unique_id: noah_climate
    device_code: 2720
    controller_data: klimaanlage_send_raw_command
    temperature_sensor: sensor.noah_zimmer_temperatur
    humidity_sensor: sensor.noah_zimmer_luftfeuchtigkeit

captive_portal:

remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 50%

# Enable logging
logger:

```

**Describe the bug**

The device 2720 does not react to any codes. Also I saw in the Thermostat UI that there are no options for swing states. Are they also bundled to the different modes?

**Debug log**

I added the log as a file to this issue

**Additional context**
Encryption key and passwords are blacked out

[home-assistant_smartir_2024-09-01T05-19-00.204Z.log](https://github.com/user-attachments/files/16827435/home-assistant_smartir_2024-09-01T05-19-00.204Z.log)
