### ISSUE TITLE
Nippon Air codes AC

### ISSUE THREAD

**Issue by salvamadrid** [smartHomeHub/SmartIR#1327]
**Home Assistant version**
2024.10.4

**SmartIR version**
1.17.9

**SmartIR configuration**

```yaml

smartir:

climate:
  - platform: smartir
    name: AC Bedroom
    unique_id: ac_bedroom
    device_code: ¿?
    controller_data: remote.bedroom_remote

```

Codes for Nippon Air AC are not there.
