### ISSUE TITLE
New Media Player SmartIR device not working

### ISSUE THREAD

**Issue by phcella** [smartHomeHub/SmartIR#1356]
Hello,

I just trying to add a new SmartIR device, but i don't know if it's nor working at all or I'm doing something wrong...

This is the configuration:
```
media_player:
#Home Theather
  - platform: smartir
    name: Home Theater
    unique_id: home_theater
    device_code: 8889
    controller_data:
      controller_type: Broadlink
      remote_entity: remote.broadlink_rm_mini3_remote
```

This is how it is appearing in HA:

![Image](https://github.com/user-attachments/assets/1a4511a4-c3b8-4a00-a320-4e1db870e8a7)
Status "Desconhecido" = "Unkown"

And this is the codes of the remote 8889.json (stored at custom_components\smartir\custom_codes\media_player):

```
{
    "manufacturer": "Philips",
    "supportedModels": [
      "MX2600"
    ],
    "supportedController": "Broadlink",
    "commandsEncoding": "Base64",
    "commands": {
        "off": "JgA0AB8cHxs8Gx8cHxsfGx8cHhwfOB8bPRseAAuZHxweHDsdHhweHB4cHh0eHB45Hh07HB4ADQUAAAAA",
        "volumeDown": "JgAwAB0eOjo6HhweHR0dHR07Oh0dHhw7HQALfR0eOjo6HhweHR0dHR07Oh0dHR07HQANBQAAAAAAAAAA",
        "volumeUp": "JgA0AB0dHR0dHjkeHB4dHhweHTo5HxweHR0dAAubHR0dHR0eOh0dHR0eHB4dOjoeHB4dHR0ADQUAAAAA",
        "mute": "JgAwAB0dOjs6HR0eHR0dHR0eHDsdHTo7HQALfRweOjs6HR0eHB4dHR0dHTsdHTo7HQANBQAAAAAAAAAA",
        "sources": {
            "TV": "JgA4ABweOR8bHxweHB4cHxw7HB4cHxweHB4cHhwAC38dHTscHh0dHR4cHhweOh4cHhweHR0dHhweAA0F",
            "AUX": "JgA0AB0dHR4cHjo6OjsdHR0eGx8dHR0dHR4cAAt+HR0dHR0eOjo6OxweHR0dHh0dHB4dHhwADQUAAAAA",
            "Tunner": "JgA4ABwfGx8dHTodHR4dOhweHR4dHR0dHR4cHh0AC30dHR0eHR06HR0eHDscHh0eHR0dHR0dHR4dAA0F"
        }
    }
}
```

It is weird, because I already have 2 SmartIR Climates working. What did I do wrong?
