### ISSUE TITLE
SmartIR climate fails with 2015.1

### ISSUE THREAD

**Issue by giofontana** [smartHomeHub/SmartIR#1361]
After upgrading HA to 2025.1 smartir stopped working. All climate objects became unavailable with the message `This entity is no longer being provided by the smartir integration. If the entity is no longer in use, delete it in settings.`

I upgraded smartir to latest version (1.18.0), but the issue persists. This is my configuration:

```
climate:
  - platform: smartir
    name: Living Room AC
    unique_id: living_ac
    device_code: 1160
    controller_data: remote.living_room
    temperature_sensor: sensor.termometer_living_room_temperature
    humidity_sensor: sensor.termometer_living_room_humidity
```
