### ISSUE TITLE
Impossible d’utiliser SmartIR avec une télécommande infrarouge Tuya

### ISSUE THREAD

**Issue by Mancier34** [smartHomeHub/SmartIR#1374]
Bonjour,

Je possède une commande infrarouge Tuya modèle iH-F8260. Modèle Zigbee TS1201. 

J’ai bien réussi à installer SmartIR via HACS.

Ma télécommande est bien reconnu sur zigbee2mqtt. 

Quand je demande d’apprendre un code, celui ci est bien appris et si je test, cela fonctionne correctement lors de l’envoi de celui-ci. 

J’ai donc créé un fichier JSON que j’ai ajouté dans smartir/codes/climate. 

J’ai ensuite rentré ma configuration dans configuration YAML 

J’ai redémarré

Et là impossible d’avoir mon entité " climate " quand je veux créer une carte thermostat. 

J’y est passé des heures je désespère ! 

Merci par avance…

**Comment by knlambert** [comment]
Hello, est-ce que tu peux partager tes configurations, et les emplacements des fichiers pour vérifier que tout est correct ?

Sinon à ta place je commencerais avec un exemple plus simple pour faire remonter le climate: genre utilise un des codes déjà disponibles [ici](https://github.com/smartHomeHub/SmartIR/tree/master/codes/climate).

Il avait été capricieux pour moi quand j'ai voulu en ajouter un deuxième et j'ai fini par me rendre compte qu'il aimait pas le `unique_id` que je lui avais donné.

Essaie donc un truc super simple:

```yaml
climate:
  - platform: smartir
    name: testsmartir
    unique_id: testsmartir
    device_code: 1023  # mets un code existant pour commencer, ça empechera pas le climate de remonter.
    controller_data: remote.ir_1 # l'entité de ta télécommande.
```
