### ISSUE TITLE
Custom code one works and the other doesn't

### ISSUE THREAD

**Issue by Cees-tech** [smartHomeHub/SmartIR#1377]
Hello,

I'm moving from Homebridge to Home Assistant. In Homebridge I have two Broadlink RM4s each controlling its own airconditioner. 

I only use cooling and heating (18-30deg) of which I already have the IR codes in HEX format. For SmartIR I made two simple, custom code JSON for these two AC units:
 
[9998.json](https://github.com/user-attachments/files/19211966/9998.json)
AircoSlaapkamerBeneden: Mitsubishi Electric MSZ-HR35VF (the JSON in SmartIR  doesn't work on my AC for cooling).

[9999.json](https://github.com/user-attachments/files/19211965/9999.json)
AircoSlaapkamerBoven: Zibro SC 3225

The AircoSlaapkamerBoven is working perfectly. The RM4 of AircoSlaapkamerBeneden only sends out the 'off' command. So with any other code the LED on the RM4 doesn't blink so nothing is transmitted...

I think it must be something simple so I hope someone sees it?
Thanks in advance!

configuration.yaml
```
smartir:

climate:
  - platform: smartir
    name: Airco slaapkamer beneden
    unique_id: AircoSlaapkamerBeneden
    device_code: 9998
    controller_data: remote.ir_airco_slaapkamer_beneden
    temperature_sensor: sensor.woonkamer_temperatuur
    humidity_sensor: sensor.woonkamer_luchtvochtigheid
    
  - platform: smartir
    name: Airco slaapkamer boven
    unique_id: AircoSlaapkamerBoven
    device_code: 9999
    controller_data: remote.wi_fi_universal_remote
    temperature_sensor: sensor.wi_fi_universal_remote_temperatuur
    humidity_sensor: sensor.wi_fi_universal_remote_luchtvochtigheid
```
