### ISSUE TITLE
Midea AC missing dry mode

### ISSUE THREAD

**Issue by FezVrasta** [smartHomeHub/SmartIR#138]
**Home Assistant version**
0.94.1

**SmartIR version**
1.5.0 (latest)

**SmartIR configuration**

```yaml

smartir:

climate:
  - platform: smartir
    name: Comfee
    unique_id: livingroom_climate
    controller_data: 10.0.0.230
    device_code: 1380
    temperature_sensor: sensor.livingroom_temperature

```

**Describe the bug**

My AC does support "dry" mode but it's not listed in the Home Assistant UI.
