### ISSUE TITLE
When I pull to homekit, not function one click.

### ISSUE THREAD

**Issue by noelesther** [smartHomeHub/SmartIR#141]
**Home Assistant version**
0.94.3
**SmartIR version**
lastest
**SmartIR configuration**
smartir:
  update_branch: rc
```yaml

Add configuration here


- platform: smartir
  name: liv ac
  unique_id: Liv_ac
  device_code: 1400
  controller_data: 192.168.1.8
  temperature_sensor: sensor.livingroom_temperature
  humidity_sensor: sensor.livingroom_humidity
  power_sensor: binary_sensor.door_window_sensor_158d00026afc66
```

**Describe the bug**

**Debug log**

```text

Add your logs here.

```

**Additional context**

Hello.

I'm using HA with homekit.

When Smartir pulled to homekit, Just click accessory not functioned.

I want to use that normal button at homekit. 

help me. thanks.
