### ISSUE TITLE
Power_sensor and SmartIR HA status out of sync.

### ISSUE THREAD

**Issue by avilao** [smartHomeHub/SmartIR#1424]
I have an AC with the following config.

```
climate:
  - platform: smartir
    name: Livingroom AC
    unique_id: livingroom_ac
    temperature_sensor: sensor.sensor_living_room_temperature_temperature
    humidity_sensor: sensor.sensor_living_room_temperature_humidity
    power_sensor: binary_sensor.livingroom_ac_power
    power_sensor_restore_state: true
    device_code: 1501 #this device_code is the .json file you produced by learning IR codes for your climate device
    controller_data: zigbee2mqtt/IRBLASTER/set/ir_code_to_send
```

The AC is on and the power_sensor is set to `on`, however the AC appears as off in HA

<img width="547" alt="Image" src="https://github.com/user-attachments/assets/e62a65bf-a02c-4be7-8b01-330c5deebf2f" />

<img width="435" alt="Image" src="https://github.com/user-attachments/assets/ac47f5c8-9879-4e99-8a5c-551404fdf202" />

Reading the docs, I was expecting the HA to display the actual state of the AC, respecting the power_sensor. 

Am I doing something wrong? Or is this behaviour not expected.

Thanks for the help.
