### ISSUE TITLE
esphome and Sony TV not working

### ISSUE THREAD

**Issue by cyrilpawelko** [smartHomeHub/SmartIR#1425]
Hello,

I'm trying to make SmartIR work with a Sony KDL42W650 TV, with a tuya IR S18 blaster.
It works with sending a single code using esphome remote_transmitter.transmit_sony command.
Esphome setup (without extra settings) : 
```
esphome:
  name: ir-s18
  friendly_name: IR-S18

bk72xx:
  board: cb3s

api:
  encryption:
    key: "mysecretkey"
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

remote_receiver:
  pin: 
    number: GPIO07
    inverted: True
    mode: INPUT_PULLUP
  dump: raw
  tolerance: 5%

remote_transmitter:
  pin: GPIO26
  carrier_duty_percent: 50%

button:
  - platform: template
    name: Sony Bravia Power Button
    on_press:
      - remote_transmitter.transmit_sony:
          data: 0x00000A90
          nbits: 12
          repeat: 3
```

HA config : 
```
smartir:

media_player:
  - platform: smartir
    name: Bravia
    unique_id: bravia_ir
    device_code: 7020
    controller_data: ir_s18_send_raw_command
    source_names:
      HDMI1: Kodi
      HDMI2: Freebox
      VGA: null
```

"Sony Bravia Power Button" works, so I know the blaster is setup properly.
When turning on from the "Media Player" in HA, I see in ESPhome logs:
`[17:58:29][D][remote_transmitter:077]: Sending remote code...`
but the TV does not turn on.

I tried to learn codes from the real remote, they are the same as in the 7020.json file.
I replaced them with the ones I learned, the behavior is still the same.
Anyway, I'm pretty confident that the codes are similar for all Sony TVs.

Do you have any idea ?
