### ISSUE TITLE
FAN_ONLY mode not recognised by LoveLace thermostat card

### ISSUE THREAD

**Issue by austwhite** [smartHomeHub/SmartIR#152]
**Home Assistant version**
0.94.3
**SmartIR version**
1.5.0
**SmartIR configuration**

```yaml
climate:
  - platform: smartir
    name: "Living room climate"
    unique_id: livingroom_ac
    device_code: 1082
    controller_data: 192.168.0.18
    temperature_sensor: sensor.living_room_temperature
```

**Describe the bug**

I have setup a custom file to include all the codes for my current air-conditioning unit and called it 1082.json.
This works well and all modes get pulled into the States UI.
The Lovelace Thermostat card is missing the Fan only setting.
I have named the Fan only setting in the JSON file as fan_only, but it still doesn't show
.
Maybe STATE_FAN_ONLY option is maybe missing from the climate.py file?
I am pretty hopeless with Python, so not sure with that :)

Additonal: This may need something separate, but how do I upload a new code file?

**Debug log**

```text

Add your logs here.

```

**Additional context**

This seems to have never been available in any versions.
