### ISSUE TITLE
hvac_mode no value

### ISSUE THREAD

**Issue by gianky69** [smartHomeHub/SmartIR#192]
I'm using SmartIR in order to control my Samsung HVAC (with device_code 1400), with no troubles until latest HA and SmartIR update.
In automations.yaml I have this commands:
```
  - alias: Accensione clima
    trigger:
      - platform: time_pattern
        minutes: '/30'
        seconds: 00
    condition:
      - condition: template
        value_template: '{{ (states.climate.climatizzatore_samsung.attributes.current_temperature | float >= (states.climate.climatizzatore_samsung.attributes.temperature | float +2))}}'
      - condition: template
        value_template: '{{ ((as_timestamp(now()) - as_timestamp(states.climate.climatizzatore_samsung.last_changed) | default(0)) | int) > 1800 }}'
      - condition: template
        value_template: '{{ (states.climate.climatizzatore_samsung.attributes.hvac_mode | string == "off" ) or (states.climate.climatizzatore_samsung.attributes.hvac_mode | string == "fan_only")}}'
      - condition: time
        after: '09:00:00'
        before: '02:00:00'
  #accendi il climatizzatore
    action:
      - service: climate.turn_on
        data:
          entity_id: climate.climatizzatore_samsung
      - delay:
          seconds: 3
      - service: climate.set_temperature
        data_template:
          entity_id: climate.climatizzatore_samsung
          temperature: '{{ states.climate.climatizzatore_samsung.attributes.temperature }}'
          hvac_mode: 'cool'
      - delay:
          seconds: 3
      - service: climate.set_fan_mode
        data_template:
          entity_id: climate.climatizzatore_samsung
          fan_mode: 'auto'
      - service: notify.ios_iphone_7_di_giancarlo
        data:
          message: "Climatizzatore Samsung acceso"
```
But checking with Template editor in HA it seems there are no response for states.climate.climatizzatore_samsung.attributes.hvac_mode.
So no more hvac_mode? But hvac_modes list all presets! How to check it now?

**Home Assistant version**
0.96.4
**SmartIR version**
1.7.0
