### ISSUE TITLE
Climate 1.0 pending implementations

### ISSUE THREAD

**Issue by benquan** [smartHomeHub/SmartIR#205]
**Home Assistant version**
0.97

**SmartIR version**
1.7.1

**SmartIR configuration**

```yaml

climate:
  - platform: smartir
    name: Room AC
    unique_id: room_ac
    device_code: 1382
    controller_data: 192.168.0.58
    temperature_sensor: sensor.room_temperature
    humidity_sensor: sensor.room_humidity

```

**Describe the bug**

There are some missing implementations from the Climate 1.0 standard according to [https://github.com/home-assistant/home-assistant/pull/23899](url)

- hvac_action **new**. The current action of the device (heating, etc. See CURRENT_HVAC_* consts)
- preset_mode **new** The current preset mode (home, away, temp) (one of preset_modes)
- preset_modes **new** The available preset modes (prefer one of PRESET_* const, custom values allowed)

I am interested in the hvac_action which is an attribute that now replaces what state used to be. So hvac_action attribute should be "cooling" or "heating" etc. This is needed so the history graph reads and displays correctly the climate entity.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/3030645/62959412-f9d92a80-bdb5-11e9-95a9-8911d68f6dbb.png">
