### ISSUE TITLE
add a new gree climate code :YAP0FB14

### ISSUE THREAD

**Issue by omegawang** [smartHomeHub/SmartIR#207]
**Home Assistant version**
0.97
**SmartIR version**
1.171
**SmartIR configuration**

```yaml
smartir:
switch:
  - platform: broadlink
    host: 192.168.1.152
    mac: '78:0F:77:5A:2D:D2'
climate:
  - platform: smartir
    name: Office AC
    unique_id: office_ac
    device_code: 1081
    controller_data: 192.168.1.152
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
media_player:
  - platform: smartir
    name: Living room TV
    unique_id: living_room_tv
    device_code: 1020
    controller_data: 192.168.1.152
    power_sensor: binary_sensor.tv_power
Add configuration here

```

**Describe the bug**

**Debug log**

```text

Add your logs here.
my gree device is: YAP0FB14
```

**Additional context**
