### ISSUE TITLE
Smartir and google assistant

### ISSUE THREAD

**Issue by jokerigno** [smartHomeHub/SmartIR#215]
**Home Assistant version**
0.97.2
**SmartIR version**
1.7.2
**SmartIR configuration**

```
binary_sensor:
  - platform: threshold
    name: "Status TV Cucina"
    entity_id: sensor.rgbplug1_energy_power
    upper: 17

media_player:
  - platform: smartir
    name: TV Cucina
    device_code: 1010
    controller_data: 192.168.2.205
    power_sensor: binary_sensor.status_tv_cucina
```

**Describe the bug**

Media players created is exposed as switch against as tv on google home app.

It would be great if media players could be used with voice commands.

**Comment by smartHomeHub** [comment]
It is not possible. Only on, off and set volume supported by the Google Assistant. To set the volume, we need the absolute value (10%, 20%, etc) which is impossible with the SmartIR integration.

**Comment by RyanEwen** [comment]
I have the same issue. I'm exposing my device as a TV and there are Volume +/- buttons on my Google Home Hub, but they have no effect. 

```
media_player:
  # Yamaha Surround (old)
  - platform: smartir
    name: Living Room Receiver
    unique_id: living_room_receiver
    device_code: 1120
    controller_data: 192.168.86.48
```

```
media_player.living_room_receiver:
  device_class: speaker
```

If the API requires absolute volumes then I understand why it doesn't work. However at some point media players in HA were updated to be a switch with the volume trait exposed to Google Assistant, so you can adjust the volume instead of the former brightness hack that was in place. I wonder if that change allows for relative volume control?

If that doesn't help, could you fake absolute volume by always exposing 50% to Google, and after a volume up, report it back to 50%, so that it never reaches 0% or 100%? Whatever you get from Google can be compared to 50% to determine whether it was a volume up vs a down. Eg, if you get 55% then it must've been a vol up. If you get 45% it must've been down.
