### ISSUE TITLE
MQTT TV

### ISSUE THREAD

**Issue by zacnut** [smartHomeHub/SmartIR#260]
**Home Assistant version**
Latest
**SmartIR version**
Latest
**SmartIR configuration**
Setup:
TV model : Hisense R6 
Replace "00:00:00:00:00:00" with MAC from phone connected to TV via RemoteNOW app.
SmartIR used to set TV channel commands as sources and change channels up and down.
```yaml
media_player:
  - platform: smartir
    name: TV
    unique_id: hisense_tv
    device_code: 6666
    controller_data: "/remoteapp/tv/ui_service/00:00:00:00:00:00$normal/actions/changechannel"
    power_sensor: sensor.tvstatus
```
Then I integrate it as a child of Universal media player to get volume_set, custom topics for main control commands (except chnl +- ), current source, current volume and wake on LAN. 
Though, any other command, like HDMI inputs and channel + - , have to be done in SmartIR, then payload reapeted to its correct topic with node-RED, like I have done with channel control.
```yaml
  - platform: universal
    device_class: tv
    name: TV
    children:
      - media_player.hisense_tv
    commands:
      turn_off:
        service: mqtt.publish
        data:
            topic: /remoteapp/tv/remote_service/00:00:00:00:00:00$normal/actions/sendkey
            payload: KEY_POWER
            qos: 2
            retain: true
      turn_on:
        service: wake_on_lan.send_magic_packet
        data:
#TV MAC
            mac: '00-00-00-00-00-00'
      volume_up:
        service: mqtt.publish
        data:
            topic: /remoteapp/tv/remote_service/00:00:00:00:00:00$normal/actions/sendkey
            payload: KEY_VOLUMEUP
            qos: 2
            retain: true
      volume_down:
        service: mqtt.publish
        data:
            topic: /remoteapp/tv/remote_service/00:00:00:00:00:00$normal/actions/sendkey
            payload: KEY_VOLUMEDOWN
            qos: 2
            retain: true
      volume_set:
        service: mqtt.publish
        data_template:
            topic: /remoteapp/tv/platform_service/00:00:00:00:00:00$normal/actions/changevolume
            payload: '{{ (volume_level * 100) }}'
    attributes:
          state: sensor.tvstatus
          volume_level: sensor.current_tv_volume
          source: sensor.tv_channel
          source_list: media_player.hisense_tv|source_list
```
6666.json
```yaml
{
    "manufacturer": "Hisense",
    "supportedModels": [
      "Unknown"
    ],
    "supportedController": "MQTT",
    "commandsEncoding": "Raw", 
    "commands": {
        "previousChannel": "KEY_CHANNELDOWN",
        "nextChannel": "KEY_CHANNELUP",
        "sources": {
	
            "ABC ME": "{\"channel_param\":\"23#ch9100439b-c0b7-4172-a4db-570c858616ea#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
          "ABC NEWS": "{\"channel_param\":\"24#ch22c86f79-947d-46ea-8bf4-2367ee047fff#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
            "ABC HD": "{\"channel_param\":\"20#ch3e386a54-26f6-4b06-877a-b3651aa07baa#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
    "ABCComedy/Kids": "{\"channel_param\":\"22#ch86380b9e-a6aa-401b-be8d-4e647aabdfc6#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
        "SBS ONE HD": "{\"channel_param\":\"30#chf8a0a8bd-708d-4926-86e5-77b37e7944cd#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
   "SBS VICELAND HD": "{\"channel_param\":\"31#ch2a5dd43e-98a5-44a4-9565-bd3ca15d42e1#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
  "SBS World Movies": "{\"channel_param\":\"32#cha72c5979-297e-431f-b99f-37fc24da49b2#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
          "SBS Food": "{\"channel_param\":\"33#chf2a11916-04ba-48f1-a239-716386a6edb9#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
    "7 HD Melbourne": "{\"channel_param\":\"70#ch65074dde-b74b-4646-b0b7-ae74bf6b7aa0#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
    "7TWO Melbourne": "{\"channel_param\":\"72#chcca4682f-a086-4005-8730-a0bc68da9562#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
     "7food network": "{\"channel_param\":\"75#chbb194309-654b-4e0f-9aa7-ea0b245af8fb#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
   "7mate Melbourne": "{\"channel_param\":\"73#ch43aa7873-d0b4-4146-be56-9ac305a9cbbd#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
   "7flix Melbourne": "{\"channel_param\":\"76#ch514c48ff-471c-413b-a714-df32b5370a7c#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
      "9HD Melbourne": "{\"channel_param\":\"90#ch8a7d2b87-c942-4838-9087-374674f11c03#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
  "9Gem HD Melbourne": "{\"channel_param\":\"95#ch8d0f9e82-786a-44cd-90ee-027bf4c9b442#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
    "9Life Melbourne": "{\"channel_param\":\"94#ch3a1e37b6-918d-4410-8a93-2d7824aeb44c#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
     "9Go! Melbourne": "{\"channel_param\":\"99#ch1fd54de9-8600-4700-ba88-ea71d9f8a320#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
              "10 HD": "{\"channel_param\":\"13#chfa306594-ee08-47f7-8824-e87f65902c0e#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
	    "10 BOLD": "{\"channel_param\":\"12#ch510d7e93-569d-4fdb-9641-5fbed2ec52f4#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
	   "10 Peach": "{\"channel_param\":\"11#chce30fa51-9cf4-44fa-ba7b-8580978d7514#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
                "C31": "{\"channel_param\":\"44#ch49c4ea42-2a7b-4d82-be18-ad3cc1e2b2a7#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
	       "TVSN": "{\"channel_param\":\"14#chca4d486f-02b3-4743-8ff9-13773ca00849#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
	    "SpreeTV": "{\"channel_param\":\"15#chcf61f062-864e-4eb6-a5b7-38fec4c456d9#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
               "NITV": "{\"channel_param\":\"34#ch0179aedb-a29d-4107-871b-67aeaa534cce#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
           "openshop": "{\"channel_param\":\"75#chbb194309-654b-4e0f-9aa7-ea0b245af8fb#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}",
         "RACING.COM": "{\"channel_param\":\"78#ch18182b4c-7110-4d9e-9a2a-c8e379e8acd0#sl35214240-16e7-4cc1-a66b-505956239f1e#4\"}"
        }
    }
}
```
**Describe the bug**
It would be amazing if volume_set could be used with MQTT so I do not need universal media player.
Also, I can only select a single topic as controller data. certain commands need different topics, so I had to use node-RED to repeat command payloads to correct topic.
Would it be possible to be able to customise topics per command?
Perhaps the same way universal does, by being able to override commands with a service call?
And of course the attributes like universal, which could be getting beyond the scope of this project .. but would be awesome.

 

**Debug log**

```text

Nil

```

**Additional context**

Not sure if anything will come of posting this, but I at least wanted to share this example to show how MQTT media player is done. Other Hisense TV models could only require a topic change and some syntax changes with key press names. [more info](https://community.home-assistant.io/t/hisense-tv-control/97638) 
I have also heard of other "smart" TVs using an MQTT app to control them , so this config could be adapted.
