### ISSUE TITLE
Volume Step and Source in HomeKit

### ISSUE THREAD

**Issue by kmplngj** [smartHomeHub/SmartIR#273]
**Home Assistant version**
0.103.5

**SmartIR version**
1.7.4

**SmartIR configuration**

```yaml
#https://github.com/smartHomeHub/SmartIR/blob/master/docs/MEDIA_PLAYER.md
smartir:     

media_player:

  #https://github.com/smartHomeHub/SmartIR/blob/master/docs/MEDIA_PLAYER.md
  - platform: smartir
    name: Wohnzimmer Verstärker
    unique_id: living_room_amp
    device_code: 9999
    controller_data: 192.168.188.62
    source_names:
      LINE1: AirPlay
      OPTICAL: TV
    power_sensor: binary_sensor.living_room_amp_state
    device_class: tv

#https://www.home-assistant.io/components/homekit/
homekit:
  auto_start: false  
  filter:
    include_entities:
      - media_player.wohnzimmer_verstarker
  entity_config:
    media_player.wohnzimmer_verstarker:
      feature_list:
        - feature: on_off
        - feature: toggle_mute
```

```json
{
    "manufacturer": "IOTAVX",
    "supportedModels": [
        "SA3"
    ],
    "supportedController": "Broadlink",
    "commandsEncoding": "Base64",
    "commands": {
        "off": "JgBQAAABKJUTEhITExMSExITEhMSExIUEhMSOBI4EjgSOBI4EjgSOBITEjkSExITFDYSExITEhQSOBITEjgSOBITEjgSOBI4EgAFNQABKEsSAA0FAAAAAAAAAAA",
        "on": "JgBQAAABKJUTEhITExMSExITEhMSExIUEhMSOBI4EjgSOBI4EjgSOBITEjkSExITFDYSExITEhQSOBITEjgSOBITEjgSOBI4EgAFNQABKEsSAA0FAAAAAAAAAAA",
        "volumeDown": "JgBYAAABK5IUERURFBEUERQRFBEVERQRFBEUNhQ2FDYVNRU1FTUVNhQRFDYUNhQ2FDYUERURFBEUNhQRFBEVERQRFDYUNhQ2FAAFMwABKkkaAAxGAAEqSBUADQU",
        "volumeUp": "JgBQAAABKZQTEhITEhQSExITEhMSExIUEhMSOBI4EjgSOBM3EjgTNxMTEjgSExI4EjgSExITEhQSOBITEjgSExMSEjgSOBM3EgAFNQABKUoSAA0FAAAAAAAAAAA",
        "mute": "JgBQAAABKJUSExIUEhMSExITEhMSFBITEhMSOBI4EzcSOBI4EjgSORITEhMTEhITEjgTExMSExISOBM3EjgSOBMTEjgSOBI4EgAFNQABKEsSAA0FAAAAAAAAAAA",
        "sources": {
            "LINE1": "JgBgAAABK5IVEBQRFBIUERQRFBEUERQSFBEUNhQ2FDYUNhI4EjgSOBI4EjgSFBITEjgSExITEhMTExITEjgSOBITEjgTNxI4EgAFNQABKEsSAAxNAAEoShQADEsAAStIFQANBQAAAAAAAAAA",
            "OPTICAL": "JgBQAAABKpIVERQRFBEUERQRFREUERQRFBEUNhQ2FTUVNRU1FTUVNhQ2FBEUNhQ2FBEUERU1FREUERQ2FBEUERU1FTUVERQ2FAAFMgABK0gUAA0FAAAAAAAAAAA"
        }
    }
}
```

**Describe the bug**

I have some question:

1. Why could I not use the volume step in HomeKit?
2. If I do a homekit.reset_accessory I see the sources in Homekit and I could use it. But sometimes if I change the source in the Lovelace UI Media Entity the device is readded to HomeKit as a new device and the source control is gone.
3. How could I save the last selected source between HA restarts?

Thanks for the great work!
Jan
