### ISSUE TITLE
Entities card header toggle

### ISSUE THREAD

**Issue by mr-blip** [smartHomeHub/SmartIR#277]
**Home Assistant version** 0.103.6

**SmartIR version** 1.7.4

**SmartIR configuration**

```yaml
entities:
  - entity: climate.bedroom_ac
    tap_action:
      action: toggle
  - entity: climate.living_ac
    tap_action:
      action: toggle
  - entity: climate.office_ac
    tap_action:
      action: toggle
title: Climate
type: entities

```

**Describe the bug**

When using lovelace entities card with climate entities, show_header_toggle doesn't switch states (toggle). Individual tap actions work fine (last state is used)

![image](https://user-images.githubusercontent.com/59650136/72256348-434dd000-3609-11ea-8985-d8da41f0b2b1.png)
