### ISSUE TITLE
Failed to connect to device

### ISSUE THREAD

**Issue by UmbeMont** [smartHomeHub/SmartIR#296]
** Home Assistant 0.105.5**

**'1.7.4'*

**SmartIR configuration**

```yaml

  - platform: smartir 
    name: Living room TV 
    unique_id: living_room_tv 
    device_code: 1060 
    controller_data: 192.168.0.42 
    power_sensor: binary_sensor.ping_tv

```

**Describe the bug**

The script work for sending 

host: 192.168.0.42
packet: "JgBGAJKVETkRORA6ERQRFBAVEBUQFRA7EDkROhAUERUQFRAUEBYQOhA6EDoPFhAVEBUQFQ8WEBUPFhAVEDoQOhA6EDoQOg8ADQUAAA=="

but does't work anymore for learning
**Debug log**

```text

2020-02-27 19:18:42 ERROR (MainThread) [homeassistant.components.broadlink] Failed to connect to device

```

**Additional context**
It was working the first days then today i tried today to see if it was working and it gave the error
