### ISSUE TITLE
Two media_player > first one scratched

### ISSUE THREAD

**Issue by epalzeolithe** [smartHomeHub/SmartIR#306]
Hello,

when i write this with 2 media_player,

```
media_player:
  - platform: smartir
    name: Onkyo
    device_code: 1300
    controller_data: 192.168.3.113
    power_sensor: binary_sensor.ampli_studio

climate:
  - platform: smartir
    name: Clim Parents
    unique_id: clim_parents
    device_code: 1281
    controller_data: 192.168.3.114
    temperature_sensor: sensor.temperature_parents
    humidity_sensor: sensor.humidity_parents
    power_sensor: binary_sensor.clim_parents

media_player:
  - platform: smartir
    name: Projecteur
    unique_id: projecteur
    device_code: 1400
    controller_data: 192.168.3.113
    power_sensor: binary_sensor.projecteur

```  

when the second_player is created, the first one become unavailable under HA

How to deal with this issue ?

Thanks

**Comment by smartHomeHub** [comment]
Please try set up your media players as below:
```
media_player:
  - platform: smartir
    name: Onkyo
    device_code: 1300
    controller_data: 192.168.3.113
    power_sensor: binary_sensor.ampli_studio
  - platform: smartir
    name: Projecteur
    unique_id: projecteur
    device_code: 1400
    controller_data: 192.168.3.113
    power_sensor: binary_sensor.projecteur
```
