### ISSUE TITLE
Cannot find device JSON file

### ISSUE THREAD

**Issue by austwhite** [smartHomeHub/SmartIR#314]
**Home Assistant version**
0.108.1
**SmartIR version**
Latest version downloaded from Github today
**SmartIR configuration**

```yaml

switch:
  - platform: broadlink
    host: 192.xxx.xxx.xxx
    mac: 'C8:xx:xx:xx:xx:xx'

climate:
  - platform: smartir
    name: Livingroom AC
    unique_id: livingroom_ac
    device_code: 1082
    controller_data: 192.xxx.xxx.xxx
    temperature_sensor: sensor.livingroom_sensor_temperature

```

I have deliberately inserted some x's.  The actual config has correct IP and MAC.
**Describe the bug**

I couldnt find this, but maybe my search is not very good.
I am unable to use SmartIR.  The RM device does not respond.
I am using an older RM3 Mini.
I am getting this error in the log:
```
Log Details (WARNING)
Logger: custom_components.smartir.climate
Source: custom_components/smartir/climate.py:63
First occurred: 11:47:25 AM (1 occurrences)
Last logged: 11:47:25 AM
```

Couldn't find the device Json file. The component will try to download it from the GitHub repo.
Issues not containing the minimum requirements will be closed:

**Debug log**

```text

Add your logs here.
Log Details (WARNING)
Logger: custom_components.smartir.climate
Source: custom_components/smartir/climate.py:63
First occurred: 11:47:25 AM (1 occurrences)
Last logged: 11:47:25 AM

Couldn't find the device Json file. The component will try to download it from the GitHub repo.
```

**Additional context**
.
