### ISSUE TITLE
Climate: ability to have different codes for "on" and "off"

### ISSUE THREAD

**Issue by chemelli74** [smartHomeHub/SmartIR#348]
**Home Assistant version**  0.110.x

**SmartIR version**  1.10.0

**SmartIR configuration**

```yaml
  - platform: smartir
    name: Condizionatore Salotto
    unique_id: salotto_ac
    device_code: 1126                       #Mitsubishi MSX09-NV II
    controller_data: !secret broadlink_ip
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
```

**Describe the bug**

Learning my codes, I discovered that "on" and "off" are 2 separate codes.
Need a way to specify "on" in json file

**Debug log**

```text
-
```
