### ISSUE TITLE
Support request: swing

### ISSUE THREAD

**Issue by chemelli74** [smartHomeHub/SmartIR#349]
**Home Assistant version** 0.110.x

**SmartIR version** 1.10.0

**SmartIR configuration**

```yaml
 - platform: smartir
    name: Condizionatore Salotto
    unique_id: salotto_ac
    device_code: 1126                       #Mitsubishi MSX09-NV II
    controller_data: !secret broadlink_ip
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
```

**Describe the bug**

I would like to understand if is possible to expose "swing" modes as shown in this picture:

![image](https://user-images.githubusercontent.com/57354320/81975850-ee0de380-9627-11ea-99e1-7b3093bc3ead.png)

**Debug log**

```text
-
```

P.S.> I tried to join telegram, but seems that the channel is no more active.
