### ISSUE TITLE
MQTT ESPEasy IR Mitsubishi Heavy AC JSON

### ISSUE THREAD

**Issue by mSapik** [smartHomeHub/SmartIR#358]
**Home Assistant version** 0.110.0

**SmartIR version** 1.11.0

**SmartIR configuration**

```yaml

  - platform: smartir
    name: "Кондиционер спальня"
    unique_id: smartir_mqtt_ac
    device_code: 6000
    controller_data: IRESP/cmd
    temperature_sensor: sensor.thbedroom_temperature
    humidity_sensor: sensor.thbedroom_humidity
    power_sensor: binary_sensor.ac_onoff_contact

```

**Additional context**

Hello thank you so much for this addon. 
Please add support for my AC, JSON is attached.
Mitsubishi Heavy Industries SRK13YJ-S, remote RKX502A001.
I use [ESPEasy HeatpumpIR](https://espeasy.readthedocs.io/en/latest/Plugin/P088.html#p088-page) he support a lot of AC's and [MQTT](https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P088_HeatpumpIR.ino).
Waiting for support of vertical and horizontal swings. 😉 

[6000.json.txt](https://github.com/smartHomeHub/SmartIR/files/4661762/6000.json.txt)
