### ISSUE TITLE
SmartIR not working when using broadlink device hostname

### ISSUE THREAD

**Issue by noob4722019** [smartHomeHub/SmartIR#359]
First of all, huge thank you for the project.

I recently reconfigured all my devices in config.yaml to use hostnames instead of IP addresses. Everything worked, except SmartIR. 

The broadlink home assistant integration still works as normal, commanding other devices, it's just SmartIR that doesn't work using hostnames.

I changed both configs back to IP, per below, and it's now working fine again. I'm on 0.110.1 and the latest smartIR.

```
climate:
  - platform: smartir
    name: Home AC
    unique_id: home_ac
    device_code: 1120
    #controller_data: RMPROPLUS-b9-38-23.lan
    controller_data: 172.16.0.134
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power  

switch:
  - platform: broadlink
    host: 172.16.0.134
    #host: RMPROPLUS-b9-38-23.lan
    mac: '*******************'
```
Let me know what info is needed. 

Thanks
