### ISSUE TITLE
Hisense and Smart IR UFO-R1 errors

### ISSUE THREAD

**Issue by anglrus** [smartHomeHub/SmartIR#362]
**Home Assistant version**
0.101
**SmartIR version**
UFO-R1
**SmartIR configuration**

```yaml

Add configuration here

1. Copy only folder SmartIR to Custom_components

2. Configuration.yaml
smartir:
  update_branch: rc
climate: !include climates.yaml

3. Climates.yaml
- platform: smartir
  name: Hisense Living Room
  unique_id: hisense_living
  device_code: 1522 # 1520, 1521, 1522
  controller_data: 192.168.1.81
  temperature_sensor: sensor.temperature
  humidity_sensor: sensor.humidity
  power_sensor: binary_sensor.ac_power

4. Switches.yaml
- platform: broadlink
  host: 192.168.1.81
  mac: '50:02:91:47:22:XX'
```

**Describe the bug**

1. ERROR:
Couldn't find the device Json file. The component will try to download it from the GitHub repo.

2. WARNING
Platform broadlink not ready yet. Retrying in 30 seconds.

3. ERROR:
Unable to find service broadlink/send
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 338, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
  File "/config/custom_components/smartir/controller.py", line 85, in send
    'broadlink', 'send', service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1212, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service broadlink/send

**Debug log**

```text

Add your logs here.

```

**Additional context**
