### ISSUE TITLE
Climate preset_modes support

### ISSUE THREAD

**Issue by Cookies1488** [smartHomeHub/SmartIR#364]
Is it possible to add support for additional operation modes for ACs?
-->

**Home Assistant version**
0.110
**SmartIR version**
1.11.0
**SmartIR configuration**

```yaml

climate:
  - platform: smartir
    name: AC
    unique_id: ac
    device_code: 1000
    controller_data: 192.168.1.30
    temperature_sensor: sensor.0x00158d0002d77de2_temperature
    humidity_sensor: sensor.0x00158d0002d77de2_humidity

```

**Describe the bug**

I've got Subtropic SUB-09HN1_18Y AC which has special turbo and sleep modes to operate.
I was trying to make my own config json file, filling it with all possible modes, but any mode that does not match with official HVAC_MODES [list ](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes)doesn't work with your component.
Examples: quiet_cool and quiet_heat modes in JSON attached

[1000.zip](https://github.com/smartHomeHub/SmartIR/files/4676879/1000.zip)

**Additional context**
