### ISSUE TITLE
MQTT Generic R51M remote JSON

### ISSUE THREAD

**Issue by alexisml** [smartHomeHub/SmartIR#366]
**Home Assistant version** 0.110.2

**SmartIR version** 1.11.0

**SmartIR configuration**

```yaml
smartir:

climate:
  - platform: smartir
    name: AC Living
    unique_id: living_ac
    device_code: 9990
    controller_data: cmnd/tasmota_ECBC40/IRhvac
```

**Additional context**

This refers to all "James" air conditioners sold at Uruguay. They use some generic chinese remote, with type: R51M/BGE. (COOLIX? protocol)

[james.json.txt](https://github.com/smartHomeHub/SmartIR/files/4692105/james.json.txt)
