### ISSUE TITLE
SmartIR causes instability with HomeKit

### ISSUE THREAD

**Issue by digitalinksol** [smartHomeHub/SmartIR#392]
**Home Assistant version**
.111.4

**SmartIR version**
1.12.0

**SmartIR configuration**

```yaml

default_config:
group: !include groups.yaml
automation: !include automations.yaml
#script: !include scripts.yaml
scene: !include scenes.yaml

bhyve:
username: xxxxxx
password: xxxxxx

switch:

platform: bhyve
platform: broadlink
host: 192.168.4.87
mac: 'XX:XX:XX:XX:XX:XX'
type:  rm_mini3_newblackbean

smartir:
check_updates: False

climate:

platform: smartir
name: Living Room Climate Control
unique_id: living_room_climate_control
device_code: 1282
controller_data: 192.168.4.87
temperature_sensor: sensor.basement_motion_sensor_temperature

```

**Describe the bug**

When SmartIR is active, all devices are inoperable in Home app (homekit) with an error message of "No Response". Attempting to repair homekit does not help. Pairing fails when smartir is active. 

Removing SmartIR solves the problem. Please let me know if any more information is needed. 

**Debug log**

```text

N/A. The log doesn’t show any errors. 

```
