### ISSUE TITLE
Toshiba RAS-10N3KV-E

### ISSUE THREAD

**Issue by Mdbset** [smartHomeHub/SmartIR#394]
**Home Assistant version**
Home Assistant 0.111.4
**SmartIR version**
1.12.0
**SmartIR configuration**

```yaml
smartir:

switch:
  - platform: broadlink
    host: 192.168.13.252
    mac: '24:DF:A7:E8:67:6C'

climate:
  - platform: smartir
    name: Air Condition
    unique_id: air_conditioner
    device_code: 3380
    controller_data: 192.168.13.252

Add configuration here

```

I use air conditioner Toshiba RAS-10N3KV-E with Broadlink RM4 mini. 
Remote control through Broadlink Universal application works fine. Now I trying to use Home Assistant. I couldn't find the code RAS-10N3KV-E among the available codes, but i found a [issue ](https://github.com/smartHomeHub/SmartIR/issues/248) that talk about model that differs by one character. I used this code, but it does't work, apperantly due to the fact that it's implemented for the xaomi controller. 
Can I adopt existing code file for another controller? If so, how do I do this?
