### ISSUE TITLE
Trotec PAC 2000 E a bit glitchy (Remote YX1F)

### ISSUE THREAD

**Issue by EpicLPer** [smartHomeHub/SmartIR#405]
**Home Assistant version**: 0.111.4

**SmartIR version**: 1.12.0

**SmartIR configuration**: 

```yaml

smartir:
    check_updates: false

climate:
  - platform: smartir
    name: Stefan Zimmer Klima
    unique_id: stefan_zimmer_klima
    device_code: 1780
    controller_data: 10.0.0.19
    temperature_sensor: sensor.temperature
    power_sensor: binary_sensor.ac_power
```

**Describe the bug**

I own a Trotec PAC 2000 E and noticed that, despite the remote being a YX1F and SmartIR offering a YX1F6 code, it's a bit glitchy. The ON command does work, however when I send an OFF command it send a "Lights Off" command instead and switches the AC unit in an unknown state since I can't see the display anymore.  
I'm not sure if this is simply an incompatible remote (since the 6 at the end is missing on my remote) or if the codes are wrong (which I doubt)? If so I'm more than happy to supply a new remote code for this specific one :)

**Debug log**

```text

Not applicable.

```

**Additional context**
