### ISSUE TITLE
Broadlink: The device storage is full?

### ISSUE THREAD

**Issue by carlos-48** [smartHomeHub/SmartIR#425]
**Home Assistant version** 0.113.0

**SmartIR version** 1.12.0

**SmartIR configuration**

```
# SmartIR para Broadlink
smartir:
#  update_branch: rc
    
# Broadlink
switch:
  - platform: broadlink
    host: 192.168.1.XYZ
    mac: '24:df:a7:31:1a:e8'

climate:
  - platform: smartir
    name: Aire
    unique_id: aire_acondicionado_salon
    device_code: 1283
    controller_data: 192.168.1.XYZ
#    temperature_sensor: sensor.temperature
#    humidity_sensor: sensor.humidity
#    power_sensor: binary_sensor.ac_power

media_player:
  - platform: smartir
    name: Tele del salon
    unique_id: tele_del_salon
    device_code: 1041
    controller_data: 192.168.1.XYZ
#    power_sensor: binary_sensor.tv_power

# broadlink nativo homeassistant
remote:
  - platform: broadlink
    host: 192.168.1.XYZ
    mac: '24:df:a7:31:1a:e8'
    type: rm4_mini
    name: broadlinkprueba
```

**Describe the bug**

I configured my RM4 Mini with the python script and everything, to work in local and not in cloud. I can make it work with Broadlink integration as a remote (I only tried to learn few codes, but it works), but i'm not able to make it work with SmartIR. I have an Air Conditioner and when I send commands, it does nothing. I can see an error in the log saying that "devide storage is full" but I still have 50GB free in the sd card.

**Debug log**

```

Logger: homeassistant.components.broadlink
Source: components/broadlink/__init__.py:120
Integration: broadlink (documentation, issues)
First occurred: 0:24:27 (5 occurrences)
Last logged: 0:24:32

Failed to send packet: The device storage is full

```

**Additional context**

Since I installed smartIR it seems that other integrations are not working properly, like SpeedTest (it gives me 0.0Mbps, but I have no network problems)
