### ISSUE TITLE
Commands not working.

### ISSUE THREAD

**Issue by PierreScerri** [smartHomeHub/SmartIR#442]
**Home Assistant version**
0.113.3
**SmartIR version**
smartir.update_component service gives 'You are already using the latest version'

**SmartIR configuration**

```yaml
- platform: smartir
  name: McQuay AC
  unique_id: mcquay_ac
  device_code: 1001
  controller_data: 192.168.1.222

This is device_code 1001.json:
{
  "manufacturer": "McQuay",
  "supportedModels": [
    "Unknown"
  ],

  "supportedController": "Broadlink",
  "commandsEncoding": "Base64",
  "minTemperature": 24,
  "maxTemperature": 24,
  "precision": 1,
  "operationModes": [
    "heat",
    "cool"
  ],
  "fanModes": [
    "low"
  ],
  "commands": {
    "off": "JgA0AJVRDxy1HA8cAAIbHA8cDhwPHA4cDxwPHA4cAAckGz8cVhxWHA8cJhw/G1ccPgAChJ4ADQUAAAAA",
    "heat": {
      "low": {
        "24": "JgA0AJVRDxy1HA8cAAIbHA8cDhwPHA4cDxwPHA4cAAckGz8cVhxWHA8cJhw/G1ccPgAChJ4ADQUAAAAA"
      }

    },
    "cool": {
      "low": {
        "24": "JgA2AJdPDxy2GxAbAAIbHA8cDxsPHA8cDxsPHA8bAAcjHT4cVhwmHD8cJhw/G24dDhwPAAKWnwANBQAA"
      }
    }
  }
}


```

**Describe the bug**
The commands are not working

**Debug log**

```text
No Errors
```

**Additional context**
Commands have been captured using the broadlink.learn service in HA.
I have only captured these two commands:
A/C Cool, Fan Low, Temp 24C, Swing ON, &
A/C Heat, Fan Low, Temp 24C, Swing ON.
Each of these commands toggles the A/C on and off.
I have used one of these commands for the 'Off' command.
