### ISSUE TITLE
Climate error After Upgrading HASSIO

### ISSUE THREAD

**Issue by netracernz** [smartHomeHub/SmartIR#482]
**Home Assistant version** 
0.115.1

**SmartIR version**
1.13.1
**SmartIR configuration**

```yaml

climate:
  - platform: smartir
    name: Panasonic Heatpump
    unique_id: lounge_heatpump
    device_code: 1021
    controller_data: 192.168.5.161
    temperature_sensor: sensor.temperature_158d000245f4c8
    humidity_sensor: sensor.humidity_158d000245f4c8

```

**Describe the bug**
Below Error On Climate control via Broadlink RM Mini after upgrading HASSIO to 115.1

**Debug log**

Unable to find service remote/send_command
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 337, in send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 101, in send
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1265, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service remote/send_command
