### ISSUE TITLE
No blast since last update

### ISSUE THREAD

**Issue by thepuncake** [smartHomeHub/SmartIR#485]
Home Assistant version -  0.115.1

SmartIR version -  1.13.2

SmartIR configuration

```yaml

media_player:
  - platform: smartir
    name: Hitachi TV
    unique_id: hitachi_tv
    device_code: 3482
    controller_data: 192.168.0.111
    power_sensor: binary_sensor.tv_power

climate:
  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac
    device_code: 1860
    controller_data: 192.168.0.111

```

Since updating hassio and smartir and broadlink integration my IR devices don't function, there is no signal received.

Debug log

```text

No errors

```
