### ISSUE TITLE
Daikin ATXC-B aircon remote does not have on or off state

### ISSUE THREAD

**Issue by ramelito** [smartHomeHub/SmartIR#487]
Description: i learned with broadlink some codes from ATXC-B Daikin aircon and found that same sequence turning on and turning off aircon. If aircon is turned off, i cannot turned it on via thermostat card in lovelace. I tried to use captured command when aircon turned on with some parameters (heat and certain temp). When i chose heat and certain temp aircon turned on, however and i chose this temp again aircon turned off;

**Home Assistant version**
0.115.2
**SmartIR version**
latest
**SmartIR configuration**

```yaml

smartir:

climate:
  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac
    device_code: 5000
    controller_data: remote.rc4_mini_remote
    temperature_sensor: sensor.xiaomi_hhccjcy01_temperature

```

**Describe the bug**

Actually this is not a bug, but kind a logic. Some aircon are not sending ON state in command, so in lovelace thermostat card is working incorrectly, as power switch for those aircons can turn off and also turn on aircons;
