### ISSUE TITLE
Error sending command Xiaomi Miio remote

### ISSUE THREAD

**Issue by pcrednet** [smartHomeHub/SmartIR#493]
I have 2 infrared emitters. a broadlink and a xiaomi miio.
The broadlink has been running smoothly for a long time. I have installed an xiaomi miio and every time I launch a command, I get an error. The codes are the same for the broadlink and the xiaomi miio since they are 2 equal machines that control.
I don't know what can happen.
Thank you.

**Home Assistant version**
Home Assistant 0.115.3

**SmartIR version**
latest

**SmartIR configuration**

```yaml

remote:
  - platform: xiaomi_miio
    host: 192.168.1.249
    token: xxxxxxxxxxxxxxXXXXXXXXXXXXxxxxxxxxx

smartir:

climate:
  - platform: smartir
    name: Buhardilla AC
    unique_id: buhardilla_ac
    device_code: 1522
    controller_data: remote.zhi_neng_yao_kong_remote
    temperature_sensor: sensor.zhi_neng_yao_kong_temperature_2
    humidity_sensor: sensor.humidity_158d000445984c
  - platform: smartir
    name: Salón AC
    unique_id: salon_ac
    device_code: 1522
    controller_data: remote.xiaomi_miio_192_168_1_249
    temperature_sensor: sensor.0x00158d00044597f7_temperature
    humidity_sensor: sensor.humidity_158d00044597f7
  

```

**Describe the bug**

Error when sending command

**Debug log**

```text

Logger: homeassistant.components.xiaomi_miio.remote
Source: components/xiaomi_miio/remote.py:244
Integration: Xiaomi Miio (documentation, issues)
First occurred: 21:40:54 (1 occurrences)
Last logged: 21:40:54

Transmit of IR command failed, b64:JgBgAQABKJITNxI4EhIRExETERQRExE5ExERORI4EhIRExEUEBQRExE5EzcSEhETERMRFBETERMRExETERMRFBETERMROhISERMRExETERMRExEUERMRFBATERMRExEUERMRExEUERMRAAEHExERORI4EhIRExEUERMRORMRETkSNxM3EzgSEhEUEBQRExETEBQRExETERQRExETERMRExETERQQFBETERQRExETERMRExETERQQFBEUEBQRExAUEBQRExETERQRExETERMRExETERQQFBETERQRExE5EjcTERE5EzgSEhE5EjgSAAEGExERExETERMRFBETERQRExETETgTEhAUERMRFBAUERMRExETERMRExEUERMRFBETERMRExETERMRExEUERMRFBATERMRFBA5EzgQOhETERMRExETERMRFBETERMRFBETERMRORETETkRORE5ExIREhMADQUAAAAAAAAAAA==, exception: Invalid command type

```

**Additional context**
I have other remote broadlink, i use same codes en both. Broadlink works perfectly but xiaomi miio not working, only this error.
