### ISSUE TITLE
SmartIR power detections

### ISSUE THREAD

**Issue by ranrinc** [smartHomeHub/SmartIR#513]
HA: 117.1
SmartIR: 1.13.2

![Screen Shot 2020-10-31 at 11 14 19 PM](https://user-images.githubusercontent.com/15801696/97784163-2651b000-1bcf-11eb-86ab-c825e7f3a205.png)

I was finally able to have a binary sensor that allowing my AC Power on/off to be detected by HA. And the status of the climate is saying ON however if you see the lovelace climate card shown not active or offline.

This is my SmartIR code.
```
# Broadlink IR AC
smartir:
climate:
  - platform: smartir
    name: Master Bed Room AC
    unique_id: mbr_ac
    device_code: 1100
    controller_data: remote.broadlink_remote_remote
    temperature_sensor: sensor.broadlink_sensor_temperature
    humidity_sensor: sensor.broadlink_sensor_humidity
    power_sensor: binary_sensor.real_bedroom_ac_plug_status
```

![Screen Shot 2020-10-31 at 11 20 39 PM](https://user-images.githubusercontent.com/15801696/97784243-bd1e6c80-1bcf-11eb-82be-9281c45530e2.png)

Hope to get some response. Thanks.
