### ISSUE TITLE
Additional Panasonic Models working with device ID 1021

### ISSUE THREAD

**Issue by gregf888** [smartHomeHub/SmartIR#542]
**Home Assistant version**
0.118.0
**SmartIR version**
I have no idea where to find that.  Just installed today 19 Dec 2020.
**SmartIR configuration**
```yaml

Add configuration here
`smartir:`
climate:
  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac
    device_code: 1021
    controller_data: remote.bedroom_remote
    temperature_sensor: sensor.ths_bedroom_temp
    humidity_sensor: sensor.ths_bedroom_humidity

  - platform: smartir
    name: Downstairs AC
    unique_id: downstairs_ac
    device_code: 1021
    controller_data: remote.lounge_remote
    temperature_sensor: sensor.ths_downstairs_temp
    humidity_sensor: sensor.ths_downstairs_humidity

  - platform: smartir
    name: Study AC
    unique_id: study_ac
    device_code: 1021
    controller_data: `remote.study_remote`


```

**Describe the bug**

Not a bug, just advising the Panasonic device code 1021 is suitable for these models:
CS-RE9PKR
CSCU-Z25TKR
**Debug log**

```text

Add your logs here.
Logs not required
```

**Additional context**
