### ISSUE TITLE
How to add multiple smartirs?

### ISSUE THREAD

**Issue by dieptang** [smartHomeHub/SmartIR#55]
I just updated to HA 0.89 version and reconfig everything works fine.
My currently device is broadlink RM Pro+ and here is the current config:

```
smartir: # Existing and works

switch:
  - platform: broadlink
    host: 192.168.1.12
    mac: 78:0f:c7:b9:15:c4
climate:
  - platform: smartir
    name: Bed AC
    device_code: 1000
    type: rm
    controller_send_service: switch.broadlink_send_packet_192_168_1_12
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
```

For now I want add Broadlink RM mini to HA, I did already with the same config above but seems not working.

```
switch: # New broadlink need works
  - platform: broadlink
    host: 192.168.1.13
    mac: 28:0f:77:b4:01:d4
climate:
  - platform: smartir
    name: Bed AC
    device_code: 1000
    type: rm
    controller_send_service: switch.broadlink_send_packet_192_168_1_13
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
```

Error:

- Duplicate "climate"

**Home Assistant version**
0.89
**SmartIR version**
1.3.9
**SmartIR configuration**

```
..\custom_components\smartir
--__init__.py
--climate.py
--controller.py
--fan.py
--media_player.py
```

**Comment by smartHomeHub** [comment]
Please configure as below

```yaml
smartir:

switch:
  - platform: broadlink
    host: 192.168.1.12
    mac: 78:0f:c7:b9:15:c4

  - platform: broadlink
    host: 192.168.1.13
    mac: 28:0f:77:b4:01:d4

climate:
  - platform: smartir
    name: AC 1
    device_code: 1000
    controller_send_service: switch.broadlink_send_packet_192_168_1_12

  - platform: smartir
    name: AC 2
    device_code: 1000
    controller_send_service: switch.broadlink_send_packet_192_168_1_13
```
