### ISSUE TITLE
Climate 1522 also work for Zephyr ZE-18CA17

### ISSUE THREAD

**Issue by sicarriere** [smartHomeHub/SmartIR#553]
**Home Assistant version**
2020.12.2
**SmartIR version**
1.13.2
**SmartIR configuration**

```yaml

climate:
  - platform: smartir
    name: Air Conditionné
    unique_id: house_ac
    device_code: 1522
    controller_data: remote.air_conditionne 

```

**Describe the bug**

Everything is working without problem on all features for th Zephyr ZE-18CA17 with the climate 1522 (Hisense DG11R2-01) with Broadlink RM4 Mini.

**Debug log**

```text

Add your logs here.

```

**Additional context**
