### ISSUE TITLE
How to use swing mode for AC

### ISSUE THREAD

**Issue by rcojr** [smartHomeHub/SmartIR#586]
**Home Assistant version**
Home Assistant Core 2021.2.3
Operating System 5.11

**SmartIR version**
SmartIR 1.16.0

**SmartIR configuration**

```yaml

smartir:

climate:
  - platform: smartir
    name: Ar Condicionado Sala
    unique_id: salatv_ac
    device_code: 1400
    controller_data: remote.broadlink_rm2_pro_remote
    temperature_sensor: sensor.mi_temperature_temperatura_sala
    humidity_sensor: sensor.mi_humidity_temperatura_sala

```

**Describe the bug**

I've read that swing mode is now compatible, and I'm trying to enable/disable swing mode of my Samsung AC, but it doesn't have and option. I tried via service: climate.set_swing_mode, but it won't do anything.
