### ISSUE TITLE
Swing Mode Toggle

### ISSUE THREAD

**Issue by SamTheGeek** [smartHomeHub/SmartIR#587]
**Home Assistant version**
Latest

**SmartIR version**
Latest

**SmartIR configuration**

```yaml

smartir:

climate:
  - platform: smartir
    name: Living Room AC
    unique_id: living_room_ac
    device_code: 1284
    controller_data: remote.living_room_ir_remote
    temperature_sensor: sensor.living_room_ir_temperature
    humidity_sensor: sensor.living_room_ir_humidity
```

**Describe the bug**

Swing Mode is only supported with unique codes per temperature. Device 1284 (AR-REG1U) sends only swing toggle codes separately.

**Additional context**

SwingMode should support toggling swing (rather than requiring swing separately for every temperature)
