### ISSUE TITLE
Thermostat stops working after a few adjustments

### ISSUE THREAD

**Issue by alexjonclement** [smartHomeHub/SmartIR#59]
**Home Assistant version**
0.89.0
**SmartIR version**
1.3.9
**SmartIR configuration**

```yaml

...
# Begin Customization
smartir:

switch:
  - platform: broadlink
    host: 192.168.1.14
    mac: '##removed##'

climate:
  - platform: smartir
    name: Air Conditioner
    unique_id: air_conditioner
    device_code: 1283
    controller_send_service: switch.broadlink_send_packet_192_168_1_14

homekit:
  filter:
    include_domains:
      - climate
    exclude_domains:
      - light


```

**Describe the bug**

Upon HomeAssistant start, usually the first few thermostat adjustments will hold. However, more temperature adjustments (whether through the HomeAssistant webpage or HomeKit) won't stick. Instead, the following error is thrown:

**Debug log**

2019-03-08 00:32:10 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit/type_thermostats.py", line 270, in update_state
    current_temp < target_temp and heat:
TypeError: '<' not supported between instances of 'NoneType' and 'float'

```

**Additional context**

I am using my own JSON that I created for my Fujitsu AR-REG1U remote. The codes should be correct, and they do work when the server reboots. I have shared it with you.
[1283.zip](https://github.com/smartHomeHub/SmartIR/files/2947161/1283.zip)
[home-assistant.log](https://github.com/smartHomeHub/SmartIR/files/2947165/home-assistant.log)
