### ISSUE TITLE
current_temperature reported as NULL

### ISSUE THREAD

**Issue by radinsky** [smartHomeHub/SmartIR#590]
**Home Assistant version**
2021.2.3

**SmartIR version**
1.16.1

**SmartIR configuration**

```yaml

- platform: smartir
  name: AC
  unique_id: ac
  device_code: 1341
  controller_data: remote.rm_pro_remote
  temperature_sensor: sensor.small_room_temperature
  humidity_sensor: sensor.small_room_humidity
  # power_sensor: binary_sensor.ac_power
```

**Describe the bug**
**current_temperature** reported as **null**

**Debug log**

```
hvac_modes: off, cool, heat
min_temp: 18
max_temp: 32
target_temp_step: 1
fan_modes: low, med, high
current_temperature: null
temperature: 22
fan_mode: low
last_on_operation: heat
device_code: 1341
manufacturer: Tadiran
supported_models: TAC490
supported_controller: Broadlink
commands_encoding: Base64
friendly_name: AC
supported_features: 9


```

![image](https://user-images.githubusercontent.com/4540268/108340618-75087180-71e1-11eb-9c2b-aab18d378556.png)
