### ISSUE TITLE
Send "on" signal only when status is "off"

### ISSUE THREAD

**Issue by simplayy** [smartHomeHub/SmartIR#621]
**Home Assistant version**
2021.4.6

**SmartIR version**
1.16.1

**SmartIR configuration**

```yaml

smartir:

climate:
  - platform: smartir
    name: Camera simo AC
    unique_id: camerasimo_ac
    device_code: 1029
    controller_data: remote.broadlink_simo_remote
    temperature_sensor: sensor.camera_simo_temperature
    humidity_sensor: sensor.camera_simo_humidity
    power_sensor: binary_sensor.ac_power


```

**Describe the bug**

Hello,
I have a Panasonic CS-V9KPG air conditioner.
when I set a temperature with associated mode it does not turn me on in the air conditioner.
so I specified the "on" signal in the json.
the problem is that the on and off signal are identical.
so when I change the temperature for a second time the air conditioner turns off.
isn't there a way to send the "on" signal only if the air conditioner has an "off" status?

Thanks
