### ISSUE TITLE
Thermostat only shows Celsius

### ISSUE THREAD

**Issue by dnschnur** [smartHomeHub/SmartIR#669]
**Home Assistant version**

core-2021.6.6

**SmartIR version**

v1.16.1

**SmartIR configuration**

```yaml
climate:
  - platform: smartir
    name: Office AC
    unique_id: office_ac
    device_code: 1281
    controller_data: remote.office_rm4_remote
    temperature_sensor: sensor.office_rm4_temperature
    humidity_sensor: sensor.office_rm4_humidity
```

**Describe the bug**

My HA instance temperature unit is Fahrenheit. The SmartIR thermostat widget shows the current temperature (large number) as e.g. "76F", which is correct. However, the target temperature (smaller number beneath) shows e.g. "22", and the allowed range is only 16 to 29. If I click the 3 dots to bring up details, I see this:

<img width="406" alt="smartir" src="https://user-images.githubusercontent.com/1678448/125178277-28c1cc00-e198-11eb-9c24-620b03c2884e.png">

So SmartIR appears to be ignoring the HA temperature unit setting.

There's no problem with the code using celsius internally, but those values should be converted to Fahrenheit when displaying them in the UI, and Fahrenheit input values should be converted to Celsius when generating IR codes. Resulting decimal values should be rounded to the nearest whole number, so e.g. 75F and 76F would both evaluate to 24C.
