### ISSUE TITLE
Adjusting temperature doesn't turn on AC

### ISSUE THREAD

**Issue by schmidtbauer** [smartHomeHub/SmartIR#670]
**Description:**

Successfully configured AC via SmartIR, all controlls are working fine with one exception. Adjusting the temperature on the thermostat does not turn on the AC. (Turn on and adjusting afterwards is working)

**Home Assistant version**
latest

**SmartIR version**
latest

**SmartIR configuration**

```yaml

climate:
  - platform: smartir
    name: Klimaanlage Wohnzimmer
    unique_id: klimaanlage_wz
    device_code: 1993
    controller_data: remote.broadlink_rm4_mini_wz_remote
    temperature_sensor: sensor.wohnzimmer_temperature
    humidity_sensor: sensor.wohnzimmer_humidity
    power_sensor: binary_sensor.ac_wz_on

```
**Json File:**

[1993.json.txt](https://github.com/smartHomeHub/SmartIR/files/6804323/1993.json.txt)

**Debug log**

```text

No Logs written at the time of adjusting temperature

```
