### ISSUE TITLE
Successfully connected to the air conditioner, but there was a problem connecting to the TV

### ISSUE THREAD

**Issue by JachinY** [smartHomeHub/SmartIR#681]
**Home Assistant version 2021.7.4

**SmartIR version 1.17.0
manifest.json
{
  "domain": "smartir",
  "name": "SmartIR",
  "documentation": "https://github.com/smartHomeHub/SmartIR",
  "dependencies": [],
  "codeowners": ["@smartHomeHub"],
  "requirements": ["aiofiles==0.6.0"],
  "homeassistant": "0.115.0",
  "version": "1.17.0",
  "updater": {
    "version": "1.17.0",
    "releaseNotes": "-- Add play_media service",
    "files": [
      "__init__.py",
      "climate.py",
      "media_player.py",
      "fan.py",
      "controller.py",
      "manifest.json",
      "services.yaml"
    ]
  }
}

**SmartIR configuration**

```yaml

Add configuration here

configuration.yaml
smartir:
  check_updates : false

climate:
  - platform: smartir
    name: Air Conditioner(Bedroom)
    unique_id: bedroom_ac
    device_code: 1960
    controller_data: remote.broadlink_remote
    temperature_sensor: sensor.temp_bedroom
    humidity_sensor: sensor.humid_bedroom
    power_sensor: binary_sensor.ac_power

media_player:
  - platform: smartir
    name: Bedroom Box
    unique_id: living_room_box
    device_code: 1380
    controller_data: remote.broadlink_remote
    power_sensor: binary_sensor.tv_power

1380.json
{
    "manufacturer": "Unknown",
    "supportedModels": [
      "Unknown"
    ],
    "supportedController": "Broadlink",
    "commandsEncoding": "Base64",
    "commands": {
        "on": "JgBQAAABKpUUEhIUEhIUERQSExITFBITEjcUNxM3FTUVNhMSFBITNxQ2FDcTOBISFTYUEhM3FBEUExISFREUNhQRFTYTEhQ3EwAFawABLEoSAA0FAAAAAAAAAAA=",
        "off": "JgBIAAABKZUUERQRFBMSEhYQExIUEhMSFTcSNxQ3EzcUNhUQFRITNhQ4FDUVNhMSEzcVEhI4ExIUERQRFBIVNRQSEzgTERU2EwANBQ==",
        "volumeDown": "JgBEABQSFBITEhURFBEUEhQRFBEVNRQ3FDYVNxM2FBIVEBQ3EzcUERU2FDYUNxMSFDYWEBUQFDgUEBURExMTOBMRFDgTAA0FAAAAAA==",
        "volumeUp": "JgBUAAABK5MUExQQFREUERQTExITExISFTYTOBQ1FDcUNhQUEhETNxQ3FDcUNhM3FDYUOBI3EzcVEhQTERITExMSExMUERMTFAAFagABKkoUAAqoCwANBQAAAAA=",
        "sources": {
            "UP": "JgBEABMSFBITEhQRFBMTEhQRFRAUNxQ2FTUVNxI3FBIUERU1FDcVNRQTExEUERQTEjgUERQRFBITOBM2FTYTOBISFDcUAA0FAAAAAA==",
            "DOWN": "JgBIAAABK5MUEhMSExMTERQSExMUEhQQFTYTNxQ4EjgTNxMTEhMTNhYRFDUUEhQ2FRAUEhQRFBMSOBMRFDcTEhQ3FTYTNhU2EwANBQ==",
            "LEFT": "JgBMAAABLJMVERMUEhMSEhMUEhITExMTEjcTNxQ3FTUTNxQTEhMUNRQTEzYUNxMSFBIUEhMSExIUNxMSFRAUNhY1FTUVNRU2FAAJAg0ADQUAAAAAAAAAAAAAAAA=",
            "RIGHT": "JgBIAAABKpQTFBISExQSEhMSFBITExMRFDcUNhQ2FDcUNhQSExIVNhMSFTUUNxM3FBEVERQRFBITNxQTFBAUERQ3FDcTNhQ3FAANBQ==",
            "OK": "JgBIAAABKpYSEhQRFBEVERURExITExMTEzYUNhQ4FDYUNRQTExEUNxQRFDYUEhMTExEUEhQRFBITNxQSEzcUNhU2FDYUNhQ2FgANBQ==",
            "HOME": "JgBQAAABKpQTEhQTEhIVEBQSExIVEhISFTYTOBI3FDYVNhQRFBITNxM3FDgSOBITExITEhQ2FhAUERQSFRIUNBQ3EzcUExM2EwAFawABK0oSAA0FAAAAAAAAAAA=",
            "BACK": "JgBYAAABK5QUEBMSFRETFBISExIUEhMTEzgSOBI3FTUUNxQRFBMSNxQ2FDYUNxM4ExITEhU1FRISEhQSExMTExI3EzcUEhQ2EwAFbAABKUoTAAJ1DAAM2QwADQU="
        }
    }
}

**Describe the bug**
My device is a Tmall Magic Box which is very similar to MiBox.
There is only the power key on the ”media_player " card, but when you click the power key, the status on the card is always displayed as off, and no other keys appear. When you click the power button on the card, you can actually control the TV on and off.

**Debug log**

```text

Add your logs here.

```

**Additional context**
