### ISSUE TITLE
Add Toshiba RAS-B07(10/13) J2KVSG-E air conditioning

### ISSUE THREAD

**Issue by gador** [smartHomeHub/SmartIR#689]
Toshiba RAS-B07(10/13) J2KVSG-E codes are missing. 
**Home Assistant version**
2021.7.4

**SmartIR version**
current master, commit 4fe2f7cb12e35979715354a207fc976393d61bef

**SmartIR configuration**

```yaml
climate:
  - platform: smartir
    name: "Living room"
    unique_id: living_room
    device_code: 1260 
    controller_data: remote.remote2_remote
```

**Describe the bug**

Unfortunatly, no of the other codes for toshiba AC units seem to work with RAS-B07(10/13) J2KVSG-E.
