### ISSUE TITLE
Cant setup smatir. Please help

### ISSUE THREAD

**Issue by CallumScarborough** [smartHomeHub/SmartIR#69]
Hi, I followed the instructions on how to set up the components but not having any luck. As soon as I check my config I am getting this error ):
![smarit](https://user-images.githubusercontent.com/48461601/54169131-5918d300-44d6-11e9-9921-4abeceaddb2b.PNG)

**Comment by alexjonclement** [comment]
Can you please paste in the contents of your configuration.yaml?

**Comment by andrewfoster** [comment]
Can you also update to the latest version of home-assistant (and include the version number in the next update on the issue)?

**Comment by CallumScarborough** [comment]
![yaml](https://user-images.githubusercontent.com/48461601/54246212-e4f33380-4598-11e9-8467-52a502a2da49.PNG)

**Comment by smartHomeHub** [comment]
Please fix the `climate` keyword indent (delete the 2 spaces)

**Comment by smartHomeHub** [comment]
```yaml
switch:
  - platform: broadlink
    host: 192.168.1.77
    mac: '00:00:00:00:00:00'

smartir:
    
climate:
  - platform: smartir
    name: Office AC
    unique_id: office_ac
    device_code: 1101
    controller_send_service: switch.broadlink_send_packet_192_168_1_77
```
