### ISSUE TITLE
remote request: Fujitsu AR-REF1E

### ISSUE THREAD

**Issue by kaizersoje** [smartHomeHub/SmartIR#691]
**Home Assistant version** 2021.8.1

**SmartIR version** 1.17.0

**SmartIR configuration**

```yaml
smartir:
  check_updates: false

climate:
  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac
    device_code: 1289
    controller_data: remote.bedroom_rm_mini_remote
    temperature_sensor: sensor.temperature_lumi_123456
    humidity_sensor: sensor.humidity_lumi_123456

```

**Describe the bug**

**Debug log**

```text

Add your logs here.

```

**Additional context**
