### ISSUE TITLE
power_sensor doesn't detect when consumption binary_sensor is on

### ISSUE THREAD

**Issue by itamarb** [smartHomeHub/SmartIR#706]
**Home Assistant version** 
2021.8.1

**SmartIR version**
1.17.0

**SmartIR configuration**

```yaml

smartir:
  check_updates: false
  
climate:
  - platform: smartir
    name: Top Floor AC Climate
    unique_id: top_floor_ac_climate
    device_code: 1620
    controller_data: remote.broadlink_top_floor_remote
    temperature_sensor: sensor.top_floor_multi_sensor_temperature
    humidity_sensor: sensor.top_floor_multi_sensor_humidity
    power_sensor: binary_sensor.is_top_floor_ac_on

```

**Describe the bug**

I have a Tuya power metering socket that gives the current consumption as an attribute on the switch device, so i have created a binary_sensor that will be either true or false if the current consumption is over 10:

```yaml
template:
  - binary_sensor:
      - name: "Is top floor ac on"
        state: "{{state_attr('switch.top_floor_ac_socket', 'current_consumption')|float > 10 }}"
```
The binary_sensor is updated correctly to on and off based on the current consumption reported by the Tuya socket attribute.
And the climate entity does get turned off when I manually turn the AC off from the remote, so it does detect the binary_sensor state. However, the climate entity doesn't turn on if I manually turn the AC on from the remote.

**Debug log**

```text

Nothing in the logs, please let me know what to look for

```

**Additional context**
