### ISSUE TITLE
A/C recognised as thermostat

### ISSUE THREAD

**Issue by chemelli74** [smartHomeHub/SmartIR#723]
**Home Assistant version**
all version, now @ 2021.9.1

**SmartIR version**
1.17.0

**SmartIR configuration**

```yaml
  - platform: smartir
    name: Condizionatore Salotto
    unique_id: ac_salotto
    device_code: 1126
    controller_data: remote.ac_salotto_remote
    temperature_sensor: sensor.sensore_salotto_temperature
    humidity_sensor: sensor.sensore_salotto_humidity
```

**Describe the bug**

Integrating Alexa via Haaska, makes the A/C (climate domain in HA) entity to be seen as a thermostat.
This means that you can only change temperature and not all the A/C properties ( like mode, speed, etc. )

Mike is convinced this is a HA code issue: https://github.com/mike-grant/haaska/issues/223

Simone

**Debug log**

```text
-
```

**Additional context**
