### ISSUE TITLE
[Info] Where is humidity sensor displayed ?

### ISSUE THREAD

**Issue by chemelli74** [smartHomeHub/SmartIR#724]
**Home Assistant version**
2021.9.1

**SmartIR version**
1.17.0

**SmartIR configuration**

```yaml
 - platform: smartir
    name: Condizionatore Salotto
    unique_id: ac_salotto
    device_code: 1126
    controller_data: remote.ac_salotto_remote
    temperature_sensor: sensor.sensore_salotto_temperature
    humidity_sensor: sensor.sensore_salotto_humidity
```

**Describe the bug**

I added the humidity sensor as per above code, but cannot see anywhere a representation of the value and if it's used at all.

**Debug log**

```text
-
```

**Additional context**

My lovelace card:

![image](https://user-images.githubusercontent.com/57354320/132092064-c0342d01-e3fa-470c-a390-469c4c8f0cb7.png)
