### ISSUE TITLE
Unable to find referenced entities climate.living_room_ac

### ISSUE THREAD

**Issue by jim1982ha** [smartHomeHub/SmartIR#740]
**Home Assistant version**  2021.10.4

**SmartIR version** 1.17.0

**SmartIR configuration**

automation.yaml:
```yaml

input_boolean:
    lr_ac_on:
      name: "Turn AC On?"
      initial: off
      icon: mdi:air-conditioner
    lr_ac_off:
      name: "Turn AC Off?"
      initial: off
      icon: mdi:air-conditioner

smartir:
  check_updates: false
#  update_branch: rc
      
climate:
  - platform: smartir
    name: Living Room AC
    unique_id: livingroom_ac
    device_code: 1
#    controller_data: home-assistant/livingroom-ac/command
    controller_data: cmnd/tasmota_ir_ctrl_1/IRhvac
#    temperature_sensor: sensor.temperature
#    humidity_sensor: sensor.humidity
#    power_sensor: binary_sensor.ac_power      


```

**Describe the bug**

I am trying to integrate SZMDLX WiFi IR (https://www.amazon.com/SZMDLX-Universal-Compatible-Automation-Controlled/dp/B082R44LJM) in HA / controlled by SmartIR.

I flashed the IR controller with Tuya-convert + push the latest IR firmware on it:

![image](https://user-images.githubusercontent.com/92262516/137445893-4f48ac32-dcea-4162-8303-8b59628db199.png)

when i press On/Off button in the remote control of the AC (i ultimately want to control in HA/SmartIR), i see the right messages in the Tasmota/ Console:

```
12:37:19.381 MQT: tele/tasmota_ir_ctrl_1/RESULT = {"IrReceived":{"Protocol":"PANASONIC_AC","Bits":216,"Data":"0x0220E004000000060220E004003928804F00000EE00000890000AD","Repeat":0,"IRHVAC":{"Vendor":"PANASONIC_AC","Model":6,"Mode":"Cool","Power":"On","Celsius":"On","Temp":20,"FanSpeed":"Low","SwingV":"Auto","SwingH":"Auto","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1}}}
01:44:51.551 MQT: tele/tasmota_ir_ctrl_1/RESULT = {"IrReceived":{"Protocol":"PANASONIC_AC","Bits":216,"Data":"0x0220E004000000060220E004003828804F00000EE00000890000AC","Repeat":0,"IRHVAC":{"Vendor":"PANASONIC_AC","Model":6,"Mode":"Cool","Power":"Off","Celsius":"On","Temp":20,"FanSpeed":"Low","SwingV":"Auto","SwingH":"Auto","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1}}}
```

I also see the device in HA / Tasmota integration:

![image](https://user-images.githubusercontent.com/92262516/137446682-335cb497-6ac2-424a-b75f-a2b3de66fa5e.png)

Following https://github.com/smartHomeHub/SmartIR, I setup SmartIR (using HCAS) and created this 1.json file in /root/config/custom_components/smartir/codes/climate:

```
//PANASONIC AC
{
    "manufacturer": "Panasonic",
    "supportedModels": [
      "CS-PUZXXX"
    ],
    "supportedController": "MQTT",
    "commandsEncoding": "Raw",
    "commands": {
        "off": "{\"Protocol\":\"PANASONIC_AC\",\"Bits\":216,\"Data\":\"0x0220E004000000060220E004003828804F00000EE00000890000AC\",\"Repeat\":0}",
        "on": "{\"Protocol\":\"PANASONIC_AC\",\"Bits\":216,\"Data\":\"0x0220E004000000060220E004003928804F00000EE00000890000AD\",\"Repeat\":0}"
    }
}

```
From here, i configured the card in Lovelace:

![image](https://user-images.githubusercontent.com/92262516/137447377-46339f38-50b1-4d9d-a4ca-74093b8f8222.png)

When I click on the "Turn On" button, i get this error in HA logs:

![image](https://user-images.githubusercontent.com/92262516/137448107-2da9e5b6-0dd7-48cc-a2bf-8d5561ea8a37.png)

![image](https://user-images.githubusercontent.com/92262516/137448277-a4146510-7c04-46b9-b1d1-bed31312f570.png)

And obviously, nothing in Tasmota device console.

I have to also add that, in parallel: these automations are working fine to turn ON/OFF the AC unit from indicated lovelace cards:

```
- id: '1587227266096'
  alias: Turn ON Living Room AC
  description: ''
  trigger:
  - entity_id: input_boolean.lr_ac_on
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: '{"Vendor":"PANASONIC_AC","Model":6,"Mode":"Cool","Power":"On","Celsius":"On","Temp":20,"FanSpeed":"Low","SwingV":"Auto","SwingH":"Auto","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1}'
      topic: cmnd/tasmota_ir_ctrl_1/IRhvac
    service: mqtt.publish

- id: '1587227266097'
  alias: Turn OFF Living Room AC
  description: ''
  trigger:
  - entity_id: input_boolean.lr_ac_off
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: '{"Vendor":"PANASONIC_AC","Power":"Off"}'
      topic: cmnd/tasmota_ir_ctrl_1/IRhvac
    service: mqtt.publish

```
Cards :

```
type: button
tap_action:
  action: toggle
entity: input_boolean.lr_ac_on
```

```
type: button
tap_action:
  action: toggle
entity: input_boolean.lr_ac_off
```

Anything I should configure more, to make the climate.living_room_ac up and running ?
Wondering what am I missing here ?
