### ISSUE TITLE
Daikin FTXS35G2V1B works with code 1100

### ISSUE THREAD

**Issue by simonjodet** [smartHomeHub/SmartIR#750]
**Home Assistant version**
Home Assistant 2021.11.1

**SmartIR version**
1.17.1

**SmartIR configuration**

```yaml

  - platform: smartir
    name: Clim Salon
    unique_id: clim_salon
    device_code: 1100
    controller_data: remote.clim_ir_remote

```

**Describe the bug**

I have a functioning control of my Daikin FTXS35G2V1B AC unit with the code 1100. I think this model can be added to the configuration.

**Debug log**

```text

Not applicable

```

**Additional context**
