### ISSUE TITLE
[new funtion] direct control with only one command

### ISSUE THREAD

**Issue by LeidenSpain** [smartHomeHub/SmartIR#76]
HI;

I'm controlling the climate with a script, but I'm forced to use several commands, in a place of one just like the thermostat card does:
```
script:
  aa_comedor_off:
    sequence:
      - condition: state
        entity_id: binary_sensor.comedor_aire_acondicionado
        state: 'on'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.aa_comedor
          operation_mode: "off"
  aa_comedor_heat:
    sequence:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.aa_comedor
          operation_mode: heat
      - delay: '00:00:02'
      - service: climate.set_temperature
        data_template:
          entity_id: climate.aa_comedor
          temperature: "{{ states.input_number.aa_comedor_temp_heat_auto.state }}"
      - delay: '00:00:02'
      - service: climate.set_fan_mode
        data:
          entity_id: climate.aa_comedor
          fan_mode: high
  aa_comedor_cool:
    sequence:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.aa_comedor
          operation_mode: cool
      - delay: '00:00:02'
      - service: climate.set_temperature
        data_template:
          entity_id: climate.aa_comedor
          temperature: "{{ states.input_number.aa_comedor_temp_cool_auto.state }}"
      - delay: '00:00:02'
      - service: climate.set_fan_mode
        data:
          entity_id: climate.aa_comedor
          fan_mode: high
```

I have tried with climate.set_temperature but it does not respond (I do not see broadcast to broadklink)
![image](https://user-images.githubusercontent.com/45803748/54496815-c754ff80-48f3-11e9-84af-ecb3a607b51c.png)

Is there no way to control it with a single command, such as when it is turned on from the thermostat card?

Regards
