### ISSUE TITLE
power_sensor base on switch not changing

### ISSUE THREAD

**Issue by ranrinc** [smartHomeHub/SmartIR#760]
**Home Assistant version**
2021.12.2

**SmartIR version**
1.17.2

**SmartIR configuration**

```yaml
  - platform: smartir
    name: Bedroom AC Climate
    unique_id: br_ac_climate
    device_code: 1114
    controller_data: remote.broadlink_rm_pro_remote
    temperature_sensor: sensor.broadlink_temp_sensor_temperature
    # humidity_sensor: sensor.broadlink_temp_sensor_humidity
    power_sensor: switch.bedroom_ac_power
```

**Describe the bug**

switch state are off however on climate the state remain on
