### ISSUE TITLE
Daikin FTXD25DVMA Working with Broadlink 1101

### ISSUE THREAD

**Issue by Daneish** [smartHomeHub/SmartIR#770]
**Home Assistant version**
 2021.12.10

**SmartIR version**
1.17.4

**SmartIR configuration**

```yaml
smartir:
  check_updates: false

climate:
  - platform: smartir
    name: Bedroom Thermostat 2
    unique_id: bedroom_generic_thermostat2
    device_code: 1101
    delay: 0.25
    controller_data: remote.broadlink_remote
    temperature_sensor: sensor.bedroom_temperature
    humidity_sensor: sensor.bedroom_humidity
```

**Describe the bug**

No bug, just reporting that climate code 1101 is working with my Daikin FTXD25DVMA Reverse Cycle Split System and Broadlink remote. I have tested all of the modes and they are all working.

**Debug log**

N/A

**Additional context**
 Thanks very much for this great project, I was very pleasantly surprised to find my system was working. Saves me painstakingly programming in 480 codes! Not to mention the awesome full featured thermostat!

Please let me know if I can provide any more information or testing to assist.
