### ISSUE TITLE
Media_player.volume_mute doesnt work

### ISSUE THREAD

**Issue by FamKeGala** [smartHomeHub/SmartIR#788]
**Home Assistant version:** OS 5.10.98
**SmartIR version:** 1.17.5
**SmartIR configuration**
```
  media_player:
    - platform: smartir
      name: TV de Andrés
      unique_id: tv_andres
      device_code: 5000
      controller_data: remote.broadlink_andres_remote
```
**Bug**

the mute service works perfectly with "volume_mute" in developer but when I put it in a button, gives me an error that it is missing the data "It_is_muted". In a button I can put it without problems but both in "media player" and "mini media player" the option does not appear.
As well as on/off, is there a mute/unmute option?

**Additional context**
