### ISSUE TITLE
Smartir Stopped working with Broadlink RM mini 4c

### ISSUE THREAD

**Issue by magusagnus** [smartHomeHub/SmartIR#803]
**Home Assistant version**

Home Assistant 2022.3.5

**SmartIR version**

1.17.5

**SmartIR configuration**

```yaml

climate:
  - platform: smartir
    name: "Ar Condicionado da Marcelle"
    unique_id: "ar_condicionado_marcelle"
    temperature_sensor: sensor.ble_temperature_a4c1386cd1d1
    humidity_sensor: sensor.ble_humidity_a4c1386cd1d1
    power_sensor: binary_sensor.estado_ar_marcelle_contact
    device_code: 1241
    controller_data: remote.marcelle_remote

```

**Describe the bug**

With the newer version of home assistant and Smartir, it stopped working with broadlink mini4c Whike didnt affect Broadlink rm4 pro. Both used to work great. After the new updates the mini4c stopped working, the rm4 pro wasn`t affected by the updates. At first i thought it was a problem with broadlink integration, so i created a button using template and added a code to turn on and off my air conditioner. It worked fine, so i discarded this possibity. 

Here is the error in home assistant log when i try to use smartir integration withe mini4c controller:

**Debug log**

 Logger: homeassistant.core
Source: util/json.py:39
First occurred: 15 de março de 2022 17:15:36 (7 occurrences)
Last logged: 02:24:15

    Error executing service: <ServiceCall remote.send_command (c:3213c051fb6ab077574b19ec7ff558d9): entity_id=['remote.marcelle_remote'], command=['b64:JgBgAQABJJQTNxM3ExIVEBQSFBIUEhQ2FBEVNhM4EhIUEhQRFREUEhMSFBEVEBQSFBIUNxM4ExITOBI4ExITEhQ4EjgTOBMSFBEVEBURFBEVERQSExIUEhQRFBEUEhQRFREVERMSFBEUAAEHExEUEhMSFBITEhQSFBIUNxMRFBITEhQSExMTEhQSExIUERQSExIUERQSFBITExMSFBEUEhMSFBEUEhQSFBITEhQRFBITEhQRFBIUEhQSExIUERQSExIUERQSFBITExMSFBEUERQSFBEUEhQSExIUEhQ3EzcTEhQRFDgTEhMTFDcSAAEHExIUERQRFBIUEhMSFBIUERQSEzgSEhQSExIUEhQSExIUERQRFBITEhQSFBITEhQSFBEYDRQSExIUEhMSFBIUEhMSFBEUERQSFBITEhQSFBITEhQRFBITEhQSExIUEhQSFBEUNhQSExIUERQSFBIUERMADQUAAAAAAAAAAA=='], delay_secs=0.5, num_repeats=1, hold_secs=0.0>

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 33, in load_json
    return json.loads(fdesc.read())  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1654, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 949, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/broadlink/remote.py", line 218, in async_send_command
    await self._async_load_storage()
  File "/usr/src/homeassistant/homeassistant/components/broadlink/remote.py", line 197, in _async_load_storage
    self._flags.update(await self._flag_storage.async_load() or {})
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 114, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 123, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 141, in _async_load_data
    data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: Expecting value: line 1 column 1 (char 0)
**Additional context**

**Comment by agneevX** [comment]
What version of Home Assistant were you using previously?

**Comment by w35l3y** [comment]
I didn't have this integration until today.
I am using `core-2022.4.0` and it is working for `media_player`.
```
media_player:
  - platform: smartir
    name: TV
    unique_id: tv_sala
    device_code: 1062
    controller_data: remote.rm4c_mini_remote # <--- RM4C Mini
    power_sensor: media_player.un55ju7500
```

**Comment by magusagnus** [comment]
> I didn't have this integration until today. I am using `core-2022.4.0` and it is working for `media_player`.
> 
> ```
> media_player:
>   - platform: smartir
>     name: TV
>     unique_id: tv_sala
>     device_code: 1062
>     controller_data: remote.rm4c_mini_remote # <--- RM4C Mini
>     power_sensor: media_player.un55ju7500
> ```

Hi @w35l3y, can you do me a favor? could you create a random Climate entity using smartir and check if the broadlink sends data when you control it using smartir?

**Comment by agneevX** [comment]
@magusagnus your original issue slipped my mind... is your JSON syntax correct?

**Comment by magusagnus** [comment]
@agneevX do you mean the remote json file? it's working when i  use it with the other broadlink model (RM 4 pro) and it was working when i was using with rm4c mini until this january update

**Comment by w35l3y** [comment]
> could you create a random Climate entity using smartir and check if the broadlink sends data when you control it using smartir?

How do I test it ? I don't have any climate next to the rm4c mini.

**Comment by magusagnus** [comment]
> > could you create a random Climate entity using smartir and check if the broadlink sends data when you control it using smartir?
> 
> How do I test it ? I don't have any climate next to the rm4c mini.

Macho, como você é conterrâneo Nordestino, fica mais fácil de explicar: Toda vez que o smartir manda um comando para o broadlink, um led azul pisca na frente do aparelho, faz um teste ai com sua integração. Se você criar um ar condicionado aleatório pelo smartir e testar, ele tem que piscar esse mesmo led azul toda vez que você ligar, desligar ou mudar a temperatura.

Usa minha config que eu coloquei la no começo como exemplo. só muda a entidade remote para o do nome que você deu quando configurou o seu mini 4c
as linhas de temperatura, umidade e potencia pode ser removidas, sao opcionais.

**Comment by w35l3y** [comment]
> Usa minha config que eu coloquei la no começo como exemplo.

```
climate:
  - platform: smartir
    name: "Ar Condicionado Teste"
    unique_id: "ar_condicionado_teste"
    device_code: 1241
    controller_data: remote.rm4c_mini_remote
```

coloquei isso... piscou tudo. o teu nem pisca ?
não apareceu nenhuma mensagem de erro no log.
