### ISSUE TITLE
Fans not retaining state after 2022.4.0 upgrade

### ISSUE THREAD

**Issue by Gio76** [smartHomeHub/SmartIR#822]
**Home Assistant version** 2022.4.0

**SmartIR version** 1.17.6 

**SmartIR configuration**

```yaml

- platform: smartir
  name: Living Room Fan
  unique_id: living_room_fan
  device_code: 1020
  controller_data: remote.broadlink_kitchen_remote
  power_sensor: binary_sensor.living_room_fan_power
```

**Describe the bug**

Since updating to HA 2022.4.0 and SmartIR 1.17.6  none of my fans are retaining their state after a HA restart. On the previous versions the fans state will always be retained after a restart or even reboot of my server.
