### ISSUE TITLE
After upgrade to 1.17.6 Broadlink not work anymore

### ISSUE THREAD

**Issue by matfil92** [smartHomeHub/SmartIR#833]
**Home Assistant version** 
Home Assistant 2022.4.7

**SmartIR version**
1.17.6

**SmartIR configuration**

```yaml
smartir:
climate:
  - platform: smartir
    name: Condizionatore Matteo
    unique_id: condizionatore_matteo
    device_code: 2020
    controller_data: remote.rm_matteo_remote
    temperature_sensor: sensor.netatmo_stazione_meteo_temperature
    humidity_sensor: sensor.netatmo_stazione_meteo_humidity
```

**Describe the bug**

After upgrade the version of smartIR to the version 1.17.6 my air conditioner of Ariston doesn't work anymore. 
I use Broadlink RM Mini and they respond correctly to the PING. I've tried also to reboot the RM Mini and Home Assistant but still doesn't work. 

After I've downgrade to the version 1.17.5 all works correctly. 

Any other people have the same issue? 
Thanks
