### ISSUE TITLE
SmartIR Climate Not Working on HA 0.89.1

### ISSUE THREAD

**Issue by jerrychong25** [smartHomeHub/SmartIR#85]
**Home Assistant version**
0.89.1

**SmartIR version**
Master Branch (Latest version as of 25th March 2019)

**SmartIR configuration**
```yaml
smartir:

switch:
  - platform: broadlink
    host: 192.168.1.XXX
    mac: 'b4:43:XX:XX:XX:XX'
    
climate:
  - platform: smartir
    name: Panasonic
    unique_id: panasonic_ac
    device_code: 1021
    controller_send_service: switch.broadlink_send_packet_192_168_1_XXX
    min_temp: 16
    max_temp: 30
    target_temp: 24
    temp_sensor: sensor.acson_temperature
    default_operation: cool
    default_fan_mode: mid
    customize:
      operations:
        - idle
        - cool
        - heat
      fan_modes:
        - low
        - mid
        - high
        - auto      
```

**Describe the bug**
Not working after migration from old ini codes to new SmartIR json codes.

**Debug log**

```text

N/A

```

**Additional context**
Screenshot:
![image](https://user-images.githubusercontent.com/15714095/55337792-e8137c80-54d1-11e9-8eee-f2ddfc874bc1.png)

Could provide any idea for troubleshooting this issue?

Thanks.

**Comment by alexeylex** [comment]
Try this
```
smartir:

switch:
  - platform: broadlink
    host: 192.168.1.XXX
    mac: 'b4:43:XX:XX:XX:XX'
    
climate:
  - platform: smartir
    name: Panasonic
    device_code: 1021
    controller_send_service: switch.broadlink_send_packet_192_168_1_XXX
    temp_sensor: sensor.acson_temperature

```
