### ISSUE TITLE
ESP8266 IR (for AC control) not sending commands

### ISSUE THREAD

**Issue by rodsolmi** [smartHomeHub/SmartIR#862]
**Home Assistant version**

Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

**SmartIR version**

1.17.6

**SmartIR configuration**

```
smartir:

climate:
  - platform: smartir
    name: AC_despacho
    unique_id: myespir
    device_code: 1385
    controller_data: myespir_send_raw_command
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power

**On the ESP_HOME side of it:**

esphome:
  name: myespir
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5XIXlxJhluG2wIIaB6vmZwet4ZEMXSo7Wd8b4WYj/3Y="
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'
  
remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 50%

ota:
  password: "9d0874ab74118ff49ccf150330bad424"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Myespir Fallback Hotspot"
    password: "y76BVR3x3wq3"


```

**Describe the bug**

I have purchased some ESP-01M (ESp8266) chipsets with built-in IR transmitter/receiver to control some ACs at home using HomeAssistant. 

In the chipset you can read the IOs:

IO4: IR_TX
IO14: IR_RX

And lucky for me, i found the exact controller for my current remote R11HG/E which corresponds to the id 1385. So far everything looked perfect.

I installed SmartIR using HACS (everything seems fine), and the chipset itself was integrated ("succesfully") via TTL directly on the raspberry that holds the HA. It connects to Wi-Fi and has a fixed IP. No issues so far.

Then I added the configuration.yaml part of it, keeping it as similar as the example, to avoid typos etc. I restarted HA, added the card for a thermostat, and it identified the entity without any issue. 

I don't know what I'm missing, but the IR simply doesn't send anything, the connection with HA seems correct, but when I operate the thermostat the log shows no response, and obviously the AC won't respond either.

**Debug log**

This is the log read by ESP OTA, it just sits there doing nothing, even if I change continously the temperature/modes, etc...

INFO Reading configuration /config/esphome/pruebair.yaml...
INFO Starting log output from myespir.local using esphome API
INFO Successfully connected to myespir.local
[13:34:10][I][app:102]: ESPHome version 2022.5.1 compiled on Jun 10 2022, 13:08:38
[13:34:10][C][wifi:491]: WiFi:
[13:34:10][C][wifi:353]:   Local MAC: 50:02:91:3C:3D:54
[13:34:10][C][wifi:354]:   SSID: [redacted]
[13:34:10][C][wifi:355]:   IP Address: 192.168.0.110
[13:34:10][C][wifi:356]:   BSSID: [redacted]
[13:34:10][C][wifi:358]:   Hostname: 'myespir'
[13:34:10][C][wifi:360]:   Signal strength: -25 dB ▂▄▆█
[13:34:10][C][wifi:364]:   Channel: 6
[13:34:10][C][wifi:365]:   Subnet: 255.255.255.0
[13:34:10][C][wifi:366]:   Gateway: 192.168.0.1
[13:34:10][C][wifi:367]:   DNS1: 192.168.0.1
[13:34:10][C][wifi:368]:   DNS2: 192.168.0.1
[13:34:10][C][logger:274]: Logger:
[13:34:10][C][logger:275]:   Level: DEBUG
[13:34:10][C][logger:276]:   Log Baud Rate: 115200
[13:34:10][C][logger:277]:   Hardware UART: UART0
[13:34:10][C][remote_transmitter:018]: Remote Transmitter...
[13:34:10][C][remote_transmitter:019]:   Carrier Duty: 50%
[13:34:10][C][remote_transmitter:020]:   Pin: GPIO14
[13:34:10][C][mdns:084]: mDNS:
[13:34:10][C][mdns:085]:   Hostname: myespir
[13:34:10][C][ota:085]: Over-The-Air Updates:
[13:34:10][C][ota:086]:   Address: myespir.local:8266
[13:34:10][C][ota:089]:   Using Password.
[13:34:10][C][api:138]: API Server:
[13:34:10][C][api:139]:   Address: myespir.local:6053
[13:34:10][C][api:141]:   Using noise encryption: YES

**Additional context**

I already have experience with HA, but I'm a complete noob when it comes to SmartIR and ESP_home "raw" programming.

Tried to understand what was going on, but i couldn't find anything.
