### ISSUE TITLE
Fan original INI file have extra ON command, so how to convert it into JSON file?

### ISSUE THREAD

**Issue by jerrychong25** [smartHomeHub/SmartIR#87]
**Home Assistant version**
0.89.1

**SmartIR version**
Master Branch (Latest version as of 25th March 2019)

**SmartIR configuration**

```yaml

smartir:

switch:
  - platform: broadlink
    host: 192.168.1.XXX
    mac: 'b4:43:XX:XX:XX:XX'

fan:
  - platform: smartir
    name: Living Room Fan
    unique_id: living_room_fan
    device_code: 9000
    controller_send_service: switch.broadlink_send_packet_192_168_1_XXX

```

**Describe the bug**

No bug, just would like to confirm whether the conversion is correct or not.

**Debug log**

Original INI file:
```
[off]
off_command = 1ww0AA0kDSQkDSQNDSQNJCQJA0kDSQNDSQNJAwAAW8AAAAA

[on]
on_command = 1ww0AA0kDSQkDQ0kDSQkDQNDSQNJCQNJA0kDQwAAW8AAAAA
                           
[left]
25 = 1ww0ACQNDSQkA0kJA0kDQ0kDSQNJCQNDSQkDQwAAW8AAAAA
50 = 1ww0AA0kDSQNJCQNDSkDQ0kDSQNJCQNDSQkDQwAAW8AAAAA
75 = 1ww0AA0kDSQNJA0k0kDSkDSQNJA0kDSQNJA0kDQwAAW8AAAAA
100 = 1ww0ACQNDSQNJA0kJA0NJC0kJA0kDSQNDSQNJAwAAW8AAAAA
```

After converted, JSON file saved in **9000.json**:
```
{
  "manufacturer": "Unknown",
  "supportedModels": [
    "Unknown"
  ],
  "supportedController": "Broadlink",
  "commandsEncoding": "Base64",
  "speed": [
    "25",
    "50",
    "75",
    "100"
  ],
  "commands": {
    "off": "1ww0AA0kDSQkDSQNDSQNJCQJA0kDSQNDSQNJAwAAW8AAAAA",
    "on": "1ww0AA0kDSQkDQ0kDSQkDQNDSQNJCQNJA0kDQwAAW8AAAAA",
    "left": {
      "25": "1ww0ACQNDSQkA0kJA0kDQ0kDSQNJCQNDSQkDQwAAW8AAAAA",
      "50": "1ww0AA0kDSQNJCQNDSkDQ0kDSQNJCQNDSQkDQwAAW8AAAAA",
      "75": "1ww0AA0kDSQNJA0k0kDSkDSQNJA0kDSQNJA0kDQwAAW8AAAAA",
      "100": "1ww0ACQNDSQNJA0kJA0NJC0kJA0kDSQNDSQNJAwAAW8AAAAA"
    }
  }
}
```

**Additional context**

My question is the **on** command INI to JSON conversion above (9000.json) correct? 

As I refer to other JSON example available in this project, but it dont have this **on** command.

Thanks.
