### ISSUE TITLE
Zigbee SmartIR ZS06

### ISSUE THREAD

**Issue by douglas-srs** [smartHomeHub/SmartIR#873]
**Home Assistant version**
2022.6.6

**SmartIR version**
1.17.6

**SmartIR configuration**
```
smartir:
    check_updates: true
```

```yaml

climate:
  - platform: smartir
    device_code: 7068
    controller_data: 'zigbee2mqtt/IR_Quarto/set'
    unique_id: climate.ar_quarto
    name: Ar Quarto
    temperature_sensor: sensor.porta_quarto_rua_device_temperature

```

I am trying to integrate my zigbee smart ir, I already created a custom device file and added it to /config/custom_components/smartir/codes/climate/7068.json

Currently, I have a script to turn on my AC and it works:

```
alias: Turn on AC
sequence:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/IR_Quarto/set
      payload: >-
        {"ir_code_to_send":"CUYCCka3Cz4j+QFAAQPfBfkB4AkBAsEB+aABAd8FQAuAA0ALAUYCgANACwLfBfngBAPgEQEBwQFAN0AHwAPgBQ/gGwEBwQGAA+ADAYBFQAUDwQH5AeAHjwO3C7cLQOdAFwP5AcEBQCdAB+AFA4ABgCOAAcALQAeAAwDBoAeAD0ABAcEB4AED4F0BQHHgDQEDtwu3C8Dn4BElgAFAw8ABwAtAB0ADQAFAB+ABAwDBIAtAA+ABE+ADAeAPF4ABAcEB4AUDAfkBwC9AAeADC+APAcAjB98F+QHfBfkB"}
mode: single
```

Here is the json file:

http://jsonblob.com/987894274578464768

And here is the MQTT log:

```
Debug 2022-06-18 22:39:55Received MQTT message on 'zigbee2mqtt/IR_Quarto/set' with data 'CUYCCka3Cz4j+QFAAQPfBfkB4AkBAsEB+aABAd8FQAuAA0ALAUYCgANACwLfBfngBAPgEQEBwQFAN0AHwAPgBQ/gGwEBwQGAA+ADAYBFQAUDwQH5AeAHjwO3C7cLQOdAFwP5AcEBQCdAB+AFA4ABgCOAAcALQAeAAwDBoAeAD0ABAcEB4AED4F0BQHHgDQEDtwu3C8Dn4BElgAFAw8ABwAtAB0ADQAFAB+ABAwDBIAtAA+ABE+ADAeAPF4ABAcEB4AUDAfkBwC9AAeADC+APAcAjB98F+QHfBfkB'
Error 2022-06-18 22:39:55Invalid message 'null', skipping...
```

The problem is that the payload needs a ir_code_to_send key before the command.

Any way to fix this?

Thanks.
