### ISSUE TITLE
AR-RCE1E - Auto 21 doesn't work

### ISSUE THREAD

**Issue by e-minguez** [smartHomeHub/SmartIR#894]
**Home Assistant version**
2022.7.3 (but it didn't worked for me since I configured it)

**SmartIR version**
61e2960e

**SmartIR configuration**

```yaml
smartir:

climate:
  - platform: smartir
    name: AC Salon
    unique_id: salon_ac
    device_code: 1285
```

**Describe the bug**

Setting auto and 21 degrees temperature doesn't work (it works 20 and 22)

**Debug log**

```text
n/a
```

**Additional context**

I guess it is just a matter of capturing the proper code here https://github.com/smartHomeHub/SmartIR/blob/master/codes/climate/1285.json#L34
