### ISSUE TITLE
Add Support for Fujitsu AR-REF2E

### ISSUE THREAD

**Issue by tbgoose** [smartHomeHub/SmartIR#908]
**Home Assistant version**
Home Assistant 2022.7.6 
Supervisor 2022.07.0 
Operating System 8.2 
Frontend 20220707.1 - latest 

**SmartIR version**
1.14 via HACS

**SmartIR configuration**

```yaml

#climate:
- platform: smartir
  name: Nursery AC
  unique_id: nursery_ac
  device_code: 1291
  controller_data: remote.rm4_mini_remote_nursery
  temperature_sensor: sensor.nursery_weather_temperature
  humidity_sensor: sensor.nursery_weather_humidity
  #power_sensor: binary_sensor.ac_power

```

**Describe the bug**

I have like to use my Broadlink RM4 mini to control my Fujitsu AR-REF2E remotes (I have three). I also have an older AR-RAJ8E remote that I could use, this also doesn't seem to be supported.

I can use the Broadlink app to successfully turn the unit on and off and interact with the AC, but not really sure if all the functions work. Happy to do some testing, just not sure how exactly as there is nothing on the actual AC to indicate what is happening, and when I use the RM4 mini to control it the remote itself doesn't seem to respond to those changes?

Edit: I have tried code 1291 for a Fujitsu AR-REF1E and nothing happens.

**Debug log**

```
2022-07-28 07:58:26 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=climate.nursery_ac, old_state=<state climate.nursery_ac=off; hvac_modes=['off', 'heat', 'cool', 'dry', 'fan_only'], min_temp=18.0, max_temp=30.0, target_temp_step=1.0, fan_modes=['auto', 'high', 'med', 'low', 'quiet'], current_temperature=22.0, temperature=18.0, fan_mode=auto, last_on_operation=cool, device_code=1291, manufacturer=Fujitsu, supported_models=['AR-REF1E'], supported_controller=Broadlink, commands_encoding=Base64, friendly_name=Nursery AC, supported_features=9 @ 2022-07-28T07:57:13.484449+10:00>, new_state=<state climate.nursery_ac=off; hvac_modes=['off', 'heat', 'cool', 'dry', 'fan_only'], min_temp=18.0, max_temp=30.0, target_temp_step=1.0, fan_modes=['auto', 'high', 'med', 'low', 'quiet'], current_temperature=22.0, temperature=18.0, current_humidity=74.23, fan_mode=auto, last_on_operation=cool, device_code=1291, manufacturer=Fujitsu, supported_models=['AR-REF1E'], supported_controller=Broadlink, commands_encoding=Base64, friendly_name=Nursery AC, supported_features=9 @ 2022-07-28T07:57:13.484449+10:00>>
```
