### ISSUE TITLE
Is there a way to uso the IFEEL functionality?

### ISSUE THREAD

**Issue by tediroca** [smartHomeHub/SmartIR#917]
**Home Assistant version**
2022.6.7

**SmartIR version**
1.17.6

**SmartIR configuration**

```yaml

climate:
  - platform: smartir
    name: AC dormitorio
    unique_id: aircon_dormitorio
    device_code: 1180
    controller_data: remote.aircon_dormitorio_remote
    temperature_sensor: sensor.sensor_clima_P1_temperature
    humidity_sensor: sensor.sensor_clima_P1_humidity
```

**Describe the bug**

Not a bug, but a feature request.

Some aircon units have the option to use the IFEEL mode, which allows reading the temperature from the remote instead of the split. This way, whenever the split is set to work at a certain temperature, the thermostat uses the temperature from the remote, making it way more accurate than the one read from the split.

This is usually enabled via the remote controller, so I was wondering if there is a way to enable this feature from SmartIR as well. I haven't played much reading the remote control codes, but can give it a go if that helps.
