### ISSUE TITLE
Mundo Clima MUPR-12-H9A works with code 1962

### ISSUE THREAD

**Issue by wojciechczyz** [smartHomeHub/SmartIR#928]
**Home Assistant version**
2022.8.2

**SmartIR version**
1.17.6

**SmartIR configuration**

```yaml

smartir:
  check_updates: true
  
climate:
  - platform: smartir
    name: Bedroom Sun AC
    unique_id: bedroom_sun_ac
    device_code: 1285
    controller_data: remote.broadlinkrm4bedroomsun_remote
  - platform: smartir
    name: Bedoom Moon AC
    unique_id: bedroom_moon_ac
    device_code: 1285
    controller_data: remote.broadlinkrm4bedroommoon_remote
  - platform: smartir
    name: Bedoom Big AC
    unique_id: bedroom_big_ac
    device_code: 1962
    controller_data: remote.broadlinkrm4bedroombig_remote
  - platform: smartir
    name: Living Room AC
    unique_id: livingroom_ac
    device_code: 1285
    controller_data: remote.broadlinkrm4livingroom_remote
```

**Describe the bug**

Code 1962 works well for Mundo Clima MUPR-12-H9A
Remote is JKR-H/102E

**Debug log**

```text

Add your logs here.

```

**Additional context**
