### ISSUE TITLE
Is able to reload new entity (media_player, climate etc.) which based on smartIR without restarting Home Assistant

### ISSUE THREAD

**Issue by dinhchinh82** [smartHomeHub/SmartIR#953]
**Home Assistant version**
2022.9.7
**SmartIR version**
1.17.6
**SmartIR configuration**

```yaml

- 
  controller_data: "remote.rm_plus_remote"
  device_code: "10201602422516"
  name: "bedroom TV"
  platform: "smartir"
  unique_id: "tivi_phong_ngu1602422516"
```

**Describe the request**

At current, each time creating new entity based on SmartIR such as media_player or Climate, it is requred to restart Home Assistant to get new entities.

Is there a way to update new entities without Restarting HA?

Thank you.
