### ISSUE TITLE
Hex codes for Esphome

### ISSUE THREAD

**Issue by vashilov** [smartHomeHub/SmartIR#958]
Sorry for my bad english.

I try add my stupid tv Samsung into smartir.
I have only HEX codes for my TV.

**Home Assistant version**
2022.10.4

**SmartIR version**
1.17.6

1) create new service send_samsung_command in my esp_home
**SmartIR configuration**
```yaml
esphome:
  name: esp_03
  platform: ESP8266
  board: nodemcuv2
api:
  password: !secret esp_password
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'
    - service: send_samsung_command
      variables:
        command: string
      then:
        - remote_transmitter.transmit_samsung:
            data: !lambda 'return strtoll(command.c_str(), NULL, 16);'
```
From HA this service work, and switсh on my TV. (code 0xE0E040BF)

2) in HA
```yaml
smartir:

media_player:
  - platform: smartir
    name: Living room TV
    unique_id: living_room_tv
    device_code: 7061
    controller_data: esp_03_send_samsung_command
    power_sensor: input_boolean.led_40
```

3) cretae codes/media_player/7061.json (Raw, but need Hex)
```yaml
{
    "manufacturer": "Samsung",
    "supportedModels": [
      "UA42J5200"
    ],
    "supportedController": "ESPHome",
    "commandsEncoding": "Raw",
    "commands": {
        "off": "0xE0E040BF", 
        "on": "0xE0E040BF",
        "previousChannel": "0xE0E008F7",
        "nextChannel": "0xE0E048B7",
        "volumeDown": "E0E0D02F",
        "volumeUp": "E0E0E01F",
        "mute": "0xE0E0F00F",
        "sources": {
            "Channel 0": "0xE0E0807F",
            "Channel 1": "0xE0E0807F",
            "Channel 2": "0xE0E0807F",
            "Channel 3": "0xE0E0807F",
            "Channel 4": "0xE0E0807F",
            "Channel 5": "0xE0E0807F",
            "Channel 6": "0xE0E0807F",
            "Channel 7": "0xE0E0807F",
            "Channel 8": "0xE0E0807F",
            "Channel 9": "0xE0E0807F",
            "Input": "0xE0E0807F"
        }
    }
}
```

Then I try push button on media_player
I have error

**Debug log**

```text

Extra data: line 1 column 2 (char 1)

Traceback (most recent call last):
  File "/config/custom_components/smartir/media_player.py", line 289, in send_command
    await self._controller.send(command)
  File "/config/custom_components/smartir/controller.py", line 183, in send
    service_data = {'command':  json.loads(command)}
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)


```

Please help me, i do not have raw codes from my TV. What i do wrong?
I need example json file for Hex codes.
