### ISSUE TITLE
[QUESTION] Don't know if this is a bug or not (think it's not)

### ISSUE THREAD

**Issue by hardwareadictos** [smartHomeHub/SmartIR#959]
**Home Assistant version** 2022.10.4

**SmartIR version** 1.17.6

**SmartIR configuration**

```yaml

smartir:
    check_updates: false
    
climate:
  - platform: smartir
    name: A/C Piso
    unique_id: ac_piso
    device_code: 1061
    controller_data: remote.broadlink_rm4_pro_comedor_remote
    temperature_sensor: sensor.despacho_temperature
    humidity_sensor: sensor.despacho_humidity
```

**Describe the bug**

Well i don't know if it's a bug or not, let me describe my environment:

I have a Broadlink RM4 Pro and a LG PREMTB001 A/C system, with the Broadlink APP i can fully control the AC wall console (it has an IR):

![image](https://user-images.githubusercontent.com/20403906/196896726-99bf7605-6055-46f2-adf9-acefb5197a05.png)

With SmartIR i can fully control this device with profile 1061https://github.com/smartHomeHub/SmartIR/blob/master/codes/climate/1061.json

And everything works absolutelly fine except one thing: Powering on the AC, i see on this profile and others that there is only an off command but not an on one:

![image](https://user-images.githubusercontent.com/20403906/196897384-c72d94dd-4ecf-4b31-be63-463699646a6f.png)

Is SmartIR able to turn on devices? I know this is not a real thermostat inside HA, but for example with Broadlink App i can turn on the device.

I tried to make HA to learn the power on command from AC console (via IR and RF), but the orange led on the RM4 Pro goes on but closes on the defined timeout without learning anything from the power button. Tried other devices at home like a FAN and a TV and all of them are working fine.

I can even turn off the AC from HA, everything works when the AC is on, the only thing icannot do is to power it up:

![image](https://user-images.githubusercontent.com/20403906/196899791-6782ef5a-80a7-43e5-ab9d-bee7478c3331.png)

Can someone explain me what is happening with that particular function?

**Debug log**

That's what i get from home assistant when i try to learn the poweron command (it does not learn anything):

```text

[139954779760352] Error handling message: Unknown error (unknown_error)
10:35:57 – (ERROR) Home Assistant WebSocket API
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Command not found: 'power'
10:35:57 – (ERROR) components/broadlink/remote.py
Failed to call remote.send_command: Command not found: 'power'
10:35:57 – (ERROR) Broadlink
Failed to learn 'power': No infrared code received within 30.0 seconds
10:35:33 – (ERROR) Broadlink

```

**Additional context**

Let me know if i can provide more information.

UPDATE1: Rear deeping into the issue, now i see that the Broadlink device is not learning any command from the A/C console (not same issue with my TV, my FAN and other devices which are learning perfectly), but SmartIR works fine for all the commands inbuilt on the 1061 profile, except for the power on thing.
