### ISSUE TITLE
Add air condition Philco PAC 18000QFM6

### ISSUE THREAD

**Issue by guicampos1** [smartHomeHub/SmartIR#978]
Hi, i have all code for air condition Philco PAC18000QFM6, how to add on app?

I have all command, how i send?

https://www.zoom.com.br/ar-condicionado/ar-condicionado-split-philco-18000-btus-pac18000qfm6

**Comment by leankuroneko** [comment]
Hi! For what I looked it seems like your AC uses a `ZH/JT-03` model remote (I think you can check that on the reverse of the remote, near the batteries). If that's the case there're already two codesets bundled [1580 and 1581](https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md#chigo).

Then you could set your device with something like this
```
climate:
  - platform: smartir
    name: A Name For Your AC
    unique_id: your_room_name_maybe
    device_code: 1580
    controller_data: remote.your_remote_device_name
```
