### ISSUE TITLE
Google Assistant and 'off', the air conditioner does not support that functionality

### ISSUE THREAD

**Issue by callifo** [smartHomeHub/SmartIR#98]
**Home Assistant version**
0.91.3
**SmartIR version**
March 6
**SmartIR configuration**

```yaml

climate:
  - platform: smartir
    name: Airconditioner
    device_code: 1000
    controller_send_service: switch.broadlink_send_packet_192_168_10_199
    temperature_sensor: sensor.living_room_temperature_f
    humidity_sensor: sensor.living_room_humidity_f

```

**Describe the bug**

When I attempt to use Google Assistant to turn off the air conditioner, it replies by saying, 'the House Airconditioner does not support that functionality'. 

This issue was present back in the Broadlink component back in the day and required the mode to be: 
'off'
in the HA config, not just: 
off

Is there a way to do the same with SmartIR as the modes are now listed in the JSON file and 'off' is no longer required even there, it's an assumed mode. 

**Debug log**

```text

N/A

```

**Additional context**
