### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by Gigiiacu** [smartHomeHub/SmartIR#986]
**Home Assistant version** Assistant 2022.12.6
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.0 - latest

**SmartIR version** ??

**SmartIR configuration**

```yaml
smartir:
climate: !include climate.yaml

Climate.yaml
  - platform: smartir
    name: Ferroli
    unique_id: Ferroli_ac
    device_code: 1180
    controller_data: remote.eremote2_remote
    temperature_sensor: sensor.temperature_Ferroli
    humidity_sensor: sensor.humidity_Ferroli
    power_sensor: binary_sensor.stato_operativo_clima_cucina
    
  - platform: smartir
    name: Sanyo
    unique_id: Sanyo_ac
    device_code: 1501
    controller_data: remote.eremote_remote
    temperature_sensor: sensor.temperature_Sanyo
    humidity_sensor: sensor.humidity_Sanyo
    power_sensor: binary_sensor.stato_operativo_clima_camere



Add configuration here

```

**Describe the bug**

doesn't work with latest update.  it gives me an error in yaml, which it didn't give before, and you can't uninstall the application.  clicking on it from unknown error

**Debug log**
after several minutes to check the configuration:
Platform error climate.smartir - Requirements for smartir not found: ['aiofiles==0.6.0'].
Platform error climate.smartir - Requirements for smartir not found: ['aiofiles==0.6.0'].
Integration error: smartir - Requirements for smartir not found: ['aiofiles==0.6.0'].

```text

Add your logs here.

```

**Additional context**
